package cn.com.cybertech.sdly.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public RoadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGlbmIsNull() {
            addCriterion("GLBM is null");
            return (Criteria) this;
        }

        public Criteria andGlbmIsNotNull() {
            addCriterion("GLBM is not null");
            return (Criteria) this;
        }

        public Criteria andGlbmEqualTo(String value) {
            addCriterion("GLBM =", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotEqualTo(String value) {
            addCriterion("GLBM <>", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmGreaterThan(String value) {
            addCriterion("GLBM >", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmGreaterThanOrEqualTo(String value) {
            addCriterion("GLBM >=", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmLessThan(String value) {
            addCriterion("GLBM <", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmLessThanOrEqualTo(String value) {
            addCriterion("GLBM <=", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmLike(String value) {
            addCriterion("GLBM like", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotLike(String value) {
            addCriterion("GLBM not like", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmIn(List<String> values) {
            addCriterion("GLBM in", values, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotIn(List<String> values) {
            addCriterion("GLBM not in", values, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmBetween(String value1, String value2) {
            addCriterion("GLBM between", value1, value2, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotBetween(String value1, String value2) {
            addCriterion("GLBM not between", value1, value2, "glbm");
            return (Criteria) this;
        }

        public Criteria andDldmIsNull() {
            addCriterion("DLDM is null");
            return (Criteria) this;
        }

        public Criteria andDldmIsNotNull() {
            addCriterion("DLDM is not null");
            return (Criteria) this;
        }

        public Criteria andDldmEqualTo(String value) {
            addCriterion("DLDM =", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmNotEqualTo(String value) {
            addCriterion("DLDM <>", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmGreaterThan(String value) {
            addCriterion("DLDM >", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmGreaterThanOrEqualTo(String value) {
            addCriterion("DLDM >=", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmLessThan(String value) {
            addCriterion("DLDM <", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmLessThanOrEqualTo(String value) {
            addCriterion("DLDM <=", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmLike(String value) {
            addCriterion("DLDM like", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmNotLike(String value) {
            addCriterion("DLDM not like", value, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmIn(List<String> values) {
            addCriterion("DLDM in", values, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmNotIn(List<String> values) {
            addCriterion("DLDM not in", values, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmBetween(String value1, String value2) {
            addCriterion("DLDM between", value1, value2, "dldm");
            return (Criteria) this;
        }

        public Criteria andDldmNotBetween(String value1, String value2) {
            addCriterion("DLDM not between", value1, value2, "dldm");
            return (Criteria) this;
        }

        public Criteria andXzqhIsNull() {
            addCriterion("xzqh is null");
            return (Criteria) this;
        }

        public Criteria andXzqhIsNotNull() {
            addCriterion("xzqh is not null");
            return (Criteria) this;
        }

        public Criteria andXzqhEqualTo(String value) {
            addCriterion("xzqh =", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotEqualTo(String value) {
            addCriterion("xzqh <>", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhGreaterThan(String value) {
            addCriterion("xzqh >", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhGreaterThanOrEqualTo(String value) {
            addCriterion("xzqh >=", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLessThan(String value) {
            addCriterion("xzqh <", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLessThanOrEqualTo(String value) {
            addCriterion("xzqh <=", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLike(String value) {
            addCriterion("xzqh like", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotLike(String value) {
            addCriterion("xzqh not like", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhIn(List<String> values) {
            addCriterion("xzqh in", values, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotIn(List<String> values) {
            addCriterion("xzqh not in", values, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhBetween(String value1, String value2) {
            addCriterion("xzqh between", value1, value2, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotBetween(String value1, String value2) {
            addCriterion("xzqh not between", value1, value2, "xzqh");
            return (Criteria) this;
        }

        public Criteria andDlmcIsNull() {
            addCriterion("dlmc is null");
            return (Criteria) this;
        }

        public Criteria andDlmcIsNotNull() {
            addCriterion("dlmc is not null");
            return (Criteria) this;
        }

        public Criteria andDlmcEqualTo(String value) {
            addCriterion("dlmc =", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcNotEqualTo(String value) {
            addCriterion("dlmc <>", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcGreaterThan(String value) {
            addCriterion("dlmc >", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcGreaterThanOrEqualTo(String value) {
            addCriterion("dlmc >=", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcLessThan(String value) {
            addCriterion("dlmc <", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcLessThanOrEqualTo(String value) {
            addCriterion("dlmc <=", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcLike(String value) {
            addCriterion("dlmc like", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcNotLike(String value) {
            addCriterion("dlmc not like", value, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcIn(List<String> values) {
            addCriterion("dlmc in", values, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcNotIn(List<String> values) {
            addCriterion("dlmc not in", values, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcBetween(String value1, String value2) {
            addCriterion("dlmc between", value1, value2, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDlmcNotBetween(String value1, String value2) {
            addCriterion("dlmc not between", value1, value2, "dlmc");
            return (Criteria) this;
        }

        public Criteria andDllxIsNull() {
            addCriterion("dllx is null");
            return (Criteria) this;
        }

        public Criteria andDllxIsNotNull() {
            addCriterion("dllx is not null");
            return (Criteria) this;
        }

        public Criteria andDllxEqualTo(String value) {
            addCriterion("dllx =", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxNotEqualTo(String value) {
            addCriterion("dllx <>", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxGreaterThan(String value) {
            addCriterion("dllx >", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxGreaterThanOrEqualTo(String value) {
            addCriterion("dllx >=", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxLessThan(String value) {
            addCriterion("dllx <", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxLessThanOrEqualTo(String value) {
            addCriterion("dllx <=", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxLike(String value) {
            addCriterion("dllx like", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxNotLike(String value) {
            addCriterion("dllx not like", value, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxIn(List<String> values) {
            addCriterion("dllx in", values, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxNotIn(List<String> values) {
            addCriterion("dllx not in", values, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxBetween(String value1, String value2) {
            addCriterion("dllx between", value1, value2, "dllx");
            return (Criteria) this;
        }

        public Criteria andDllxNotBetween(String value1, String value2) {
            addCriterion("dllx not between", value1, value2, "dllx");
            return (Criteria) this;
        }

        public Criteria andGlxzdjIsNull() {
            addCriterion("GLXZDJ is null");
            return (Criteria) this;
        }

        public Criteria andGlxzdjIsNotNull() {
            addCriterion("GLXZDJ is not null");
            return (Criteria) this;
        }

        public Criteria andGlxzdjEqualTo(String value) {
            addCriterion("GLXZDJ =", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjNotEqualTo(String value) {
            addCriterion("GLXZDJ <>", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjGreaterThan(String value) {
            addCriterion("GLXZDJ >", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjGreaterThanOrEqualTo(String value) {
            addCriterion("GLXZDJ >=", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjLessThan(String value) {
            addCriterion("GLXZDJ <", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjLessThanOrEqualTo(String value) {
            addCriterion("GLXZDJ <=", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjLike(String value) {
            addCriterion("GLXZDJ like", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjNotLike(String value) {
            addCriterion("GLXZDJ not like", value, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjIn(List<String> values) {
            addCriterion("GLXZDJ in", values, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjNotIn(List<String> values) {
            addCriterion("GLXZDJ not in", values, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjBetween(String value1, String value2) {
            addCriterion("GLXZDJ between", value1, value2, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andGlxzdjNotBetween(String value1, String value2) {
            addCriterion("GLXZDJ not between", value1, value2, "glxzdj");
            return (Criteria) this;
        }

        public Criteria andDxIsNull() {
            addCriterion("dx is null");
            return (Criteria) this;
        }

        public Criteria andDxIsNotNull() {
            addCriterion("dx is not null");
            return (Criteria) this;
        }

        public Criteria andDxEqualTo(String value) {
            addCriterion("dx =", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxNotEqualTo(String value) {
            addCriterion("dx <>", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxGreaterThan(String value) {
            addCriterion("dx >", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxGreaterThanOrEqualTo(String value) {
            addCriterion("dx >=", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxLessThan(String value) {
            addCriterion("dx <", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxLessThanOrEqualTo(String value) {
            addCriterion("dx <=", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxLike(String value) {
            addCriterion("dx like", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxNotLike(String value) {
            addCriterion("dx not like", value, "dx");
            return (Criteria) this;
        }

        public Criteria andDxIn(List<String> values) {
            addCriterion("dx in", values, "dx");
            return (Criteria) this;
        }

        public Criteria andDxNotIn(List<String> values) {
            addCriterion("dx not in", values, "dx");
            return (Criteria) this;
        }

        public Criteria andDxBetween(String value1, String value2) {
            addCriterion("dx between", value1, value2, "dx");
            return (Criteria) this;
        }

        public Criteria andDxNotBetween(String value1, String value2) {
            addCriterion("dx not between", value1, value2, "dx");
            return (Criteria) this;
        }

        public Criteria andDlxxIsNull() {
            addCriterion("dlxx is null");
            return (Criteria) this;
        }

        public Criteria andDlxxIsNotNull() {
            addCriterion("dlxx is not null");
            return (Criteria) this;
        }

        public Criteria andDlxxEqualTo(String value) {
            addCriterion("dlxx =", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxNotEqualTo(String value) {
            addCriterion("dlxx <>", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxGreaterThan(String value) {
            addCriterion("dlxx >", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxGreaterThanOrEqualTo(String value) {
            addCriterion("dlxx >=", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxLessThan(String value) {
            addCriterion("dlxx <", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxLessThanOrEqualTo(String value) {
            addCriterion("dlxx <=", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxLike(String value) {
            addCriterion("dlxx like", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxNotLike(String value) {
            addCriterion("dlxx not like", value, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxIn(List<String> values) {
            addCriterion("dlxx in", values, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxNotIn(List<String> values) {
            addCriterion("dlxx not in", values, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxBetween(String value1, String value2) {
            addCriterion("dlxx between", value1, value2, "dlxx");
            return (Criteria) this;
        }

        public Criteria andDlxxNotBetween(String value1, String value2) {
            addCriterion("dlxx not between", value1, value2, "dlxx");
            return (Criteria) this;
        }

        public Criteria andLkldlxIsNull() {
            addCriterion("lkldlx is null");
            return (Criteria) this;
        }

        public Criteria andLkldlxIsNotNull() {
            addCriterion("lkldlx is not null");
            return (Criteria) this;
        }

        public Criteria andLkldlxEqualTo(String value) {
            addCriterion("lkldlx =", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxNotEqualTo(String value) {
            addCriterion("lkldlx <>", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxGreaterThan(String value) {
            addCriterion("lkldlx >", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxGreaterThanOrEqualTo(String value) {
            addCriterion("lkldlx >=", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxLessThan(String value) {
            addCriterion("lkldlx <", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxLessThanOrEqualTo(String value) {
            addCriterion("lkldlx <=", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxLike(String value) {
            addCriterion("lkldlx like", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxNotLike(String value) {
            addCriterion("lkldlx not like", value, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxIn(List<String> values) {
            addCriterion("lkldlx in", values, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxNotIn(List<String> values) {
            addCriterion("lkldlx not in", values, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxBetween(String value1, String value2) {
            addCriterion("lkldlx between", value1, value2, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andLkldlxNotBetween(String value1, String value2) {
            addCriterion("lkldlx not between", value1, value2, "lkldlx");
            return (Criteria) this;
        }

        public Criteria andDlwdglIsNull() {
            addCriterion("dlwdgl is null");
            return (Criteria) this;
        }

        public Criteria andDlwdglIsNotNull() {
            addCriterion("dlwdgl is not null");
            return (Criteria) this;
        }

        public Criteria andDlwdglEqualTo(String value) {
            addCriterion("dlwdgl =", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglNotEqualTo(String value) {
            addCriterion("dlwdgl <>", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglGreaterThan(String value) {
            addCriterion("dlwdgl >", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglGreaterThanOrEqualTo(String value) {
            addCriterion("dlwdgl >=", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglLessThan(String value) {
            addCriterion("dlwdgl <", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglLessThanOrEqualTo(String value) {
            addCriterion("dlwdgl <=", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglLike(String value) {
            addCriterion("dlwdgl like", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglNotLike(String value) {
            addCriterion("dlwdgl not like", value, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglIn(List<String> values) {
            addCriterion("dlwdgl in", values, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglNotIn(List<String> values) {
            addCriterion("dlwdgl not in", values, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglBetween(String value1, String value2) {
            addCriterion("dlwdgl between", value1, value2, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andDlwdglNotBetween(String value1, String value2) {
            addCriterion("dlwdgl not between", value1, value2, "dlwdgl");
            return (Criteria) this;
        }

        public Criteria andLmjgIsNull() {
            addCriterion("lmjg is null");
            return (Criteria) this;
        }

        public Criteria andLmjgIsNotNull() {
            addCriterion("lmjg is not null");
            return (Criteria) this;
        }

        public Criteria andLmjgEqualTo(String value) {
            addCriterion("lmjg =", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgNotEqualTo(String value) {
            addCriterion("lmjg <>", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgGreaterThan(String value) {
            addCriterion("lmjg >", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgGreaterThanOrEqualTo(String value) {
            addCriterion("lmjg >=", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgLessThan(String value) {
            addCriterion("lmjg <", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgLessThanOrEqualTo(String value) {
            addCriterion("lmjg <=", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgLike(String value) {
            addCriterion("lmjg like", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgNotLike(String value) {
            addCriterion("lmjg not like", value, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgIn(List<String> values) {
            addCriterion("lmjg in", values, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgNotIn(List<String> values) {
            addCriterion("lmjg not in", values, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgBetween(String value1, String value2) {
            addCriterion("lmjg between", value1, value2, "lmjg");
            return (Criteria) this;
        }

        public Criteria andLmjgNotBetween(String value1, String value2) {
            addCriterion("lmjg not between", value1, value2, "lmjg");
            return (Criteria) this;
        }

        public Criteria andFhsslxIsNull() {
            addCriterion("fhsslx is null");
            return (Criteria) this;
        }

        public Criteria andFhsslxIsNotNull() {
            addCriterion("fhsslx is not null");
            return (Criteria) this;
        }

        public Criteria andFhsslxEqualTo(String value) {
            addCriterion("fhsslx =", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxNotEqualTo(String value) {
            addCriterion("fhsslx <>", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxGreaterThan(String value) {
            addCriterion("fhsslx >", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxGreaterThanOrEqualTo(String value) {
            addCriterion("fhsslx >=", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxLessThan(String value) {
            addCriterion("fhsslx <", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxLessThanOrEqualTo(String value) {
            addCriterion("fhsslx <=", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxLike(String value) {
            addCriterion("fhsslx like", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxNotLike(String value) {
            addCriterion("fhsslx not like", value, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxIn(List<String> values) {
            addCriterion("fhsslx in", values, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxNotIn(List<String> values) {
            addCriterion("fhsslx not in", values, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxBetween(String value1, String value2) {
            addCriterion("fhsslx between", value1, value2, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andFhsslxNotBetween(String value1, String value2) {
            addCriterion("fhsslx not between", value1, value2, "fhsslx");
            return (Criteria) this;
        }

        public Criteria andQsIsNull() {
            addCriterion("qs is null");
            return (Criteria) this;
        }

        public Criteria andQsIsNotNull() {
            addCriterion("qs is not null");
            return (Criteria) this;
        }

        public Criteria andQsEqualTo(String value) {
            addCriterion("qs =", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsNotEqualTo(String value) {
            addCriterion("qs <>", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsGreaterThan(String value) {
            addCriterion("qs >", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsGreaterThanOrEqualTo(String value) {
            addCriterion("qs >=", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsLessThan(String value) {
            addCriterion("qs <", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsLessThanOrEqualTo(String value) {
            addCriterion("qs <=", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsLike(String value) {
            addCriterion("qs like", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsNotLike(String value) {
            addCriterion("qs not like", value, "qs");
            return (Criteria) this;
        }

        public Criteria andQsIn(List<String> values) {
            addCriterion("qs in", values, "qs");
            return (Criteria) this;
        }

        public Criteria andQsNotIn(List<String> values) {
            addCriterion("qs not in", values, "qs");
            return (Criteria) this;
        }

        public Criteria andQsBetween(String value1, String value2) {
            addCriterion("qs between", value1, value2, "qs");
            return (Criteria) this;
        }

        public Criteria andQsNotBetween(String value1, String value2) {
            addCriterion("qs not between", value1, value2, "qs");
            return (Criteria) this;
        }

        public Criteria andJsIsNull() {
            addCriterion("js is null");
            return (Criteria) this;
        }

        public Criteria andJsIsNotNull() {
            addCriterion("js is not null");
            return (Criteria) this;
        }

        public Criteria andJsEqualTo(String value) {
            addCriterion("js =", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsNotEqualTo(String value) {
            addCriterion("js <>", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsGreaterThan(String value) {
            addCriterion("js >", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsGreaterThanOrEqualTo(String value) {
            addCriterion("js >=", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsLessThan(String value) {
            addCriterion("js <", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsLessThanOrEqualTo(String value) {
            addCriterion("js <=", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsLike(String value) {
            addCriterion("js like", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsNotLike(String value) {
            addCriterion("js not like", value, "js");
            return (Criteria) this;
        }

        public Criteria andJsIn(List<String> values) {
            addCriterion("js in", values, "js");
            return (Criteria) this;
        }

        public Criteria andJsNotIn(List<String> values) {
            addCriterion("js not in", values, "js");
            return (Criteria) this;
        }

        public Criteria andJsBetween(String value1, String value2) {
            addCriterion("js between", value1, value2, "js");
            return (Criteria) this;
        }

        public Criteria andJsNotBetween(String value1, String value2) {
            addCriterion("js not between", value1, value2, "js");
            return (Criteria) this;
        }

        public Criteria andXqlcIsNull() {
            addCriterion("XQLC is null");
            return (Criteria) this;
        }

        public Criteria andXqlcIsNotNull() {
            addCriterion("XQLC is not null");
            return (Criteria) this;
        }

        public Criteria andXqlcEqualTo(Integer value) {
            addCriterion("XQLC =", value, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcNotEqualTo(Integer value) {
            addCriterion("XQLC <>", value, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcGreaterThan(Integer value) {
            addCriterion("XQLC >", value, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcGreaterThanOrEqualTo(Integer value) {
            addCriterion("XQLC >=", value, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcLessThan(Integer value) {
            addCriterion("XQLC <", value, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcLessThanOrEqualTo(Integer value) {
            addCriterion("XQLC <=", value, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcIn(List<Integer> values) {
            addCriterion("XQLC in", values, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcNotIn(List<Integer> values) {
            addCriterion("XQLC not in", values, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcBetween(Integer value1, Integer value2) {
            addCriterion("XQLC between", value1, value2, "xqlc");
            return (Criteria) this;
        }

        public Criteria andXqlcNotBetween(Integer value1, Integer value2) {
            addCriterion("XQLC not between", value1, value2, "xqlc");
            return (Criteria) this;
        }

        public Criteria andCjrIsNull() {
            addCriterion("cjr is null");
            return (Criteria) this;
        }

        public Criteria andCjrIsNotNull() {
            addCriterion("cjr is not null");
            return (Criteria) this;
        }

        public Criteria andCjrEqualTo(String value) {
            addCriterion("cjr =", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotEqualTo(String value) {
            addCriterion("cjr <>", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThan(String value) {
            addCriterion("cjr >", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThanOrEqualTo(String value) {
            addCriterion("cjr >=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThan(String value) {
            addCriterion("cjr <", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThanOrEqualTo(String value) {
            addCriterion("cjr <=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLike(String value) {
            addCriterion("cjr like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotLike(String value) {
            addCriterion("cjr not like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrIn(List<String> values) {
            addCriterion("cjr in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotIn(List<String> values) {
            addCriterion("cjr not in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrBetween(String value1, String value2) {
            addCriterion("cjr between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotBetween(String value1, String value2) {
            addCriterion("cjr not between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNull() {
            addCriterion("cjsj is null");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNotNull() {
            addCriterion("cjsj is not null");
            return (Criteria) this;
        }

        public Criteria andCjsjEqualTo(Date value) {
            addCriterion("cjsj =", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotEqualTo(Date value) {
            addCriterion("cjsj <>", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThan(Date value) {
            addCriterion("cjsj >", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThanOrEqualTo(Date value) {
            addCriterion("cjsj >=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThan(Date value) {
            addCriterion("cjsj <", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThanOrEqualTo(Date value) {
            addCriterion("cjsj <=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjIn(List<Date> values) {
            addCriterion("cjsj in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotIn(List<Date> values) {
            addCriterion("cjsj not in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjBetween(Date value1, Date value2) {
            addCriterion("cjsj between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotBetween(Date value1, Date value2) {
            addCriterion("cjsj not between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andGxsjIsNull() {
            addCriterion("gxsj is null");
            return (Criteria) this;
        }

        public Criteria andGxsjIsNotNull() {
            addCriterion("gxsj is not null");
            return (Criteria) this;
        }

        public Criteria andGxsjEqualTo(Date value) {
            addCriterion("gxsj =", value, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjNotEqualTo(Date value) {
            addCriterion("gxsj <>", value, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjGreaterThan(Date value) {
            addCriterion("gxsj >", value, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjGreaterThanOrEqualTo(Date value) {
            addCriterion("gxsj >=", value, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjLessThan(Date value) {
            addCriterion("gxsj <", value, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjLessThanOrEqualTo(Date value) {
            addCriterion("gxsj <=", value, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjIn(List<Date> values) {
            addCriterion("gxsj in", values, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjNotIn(List<Date> values) {
            addCriterion("gxsj not in", values, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjBetween(Date value1, Date value2) {
            addCriterion("gxsj between", value1, value2, "gxsj");
            return (Criteria) this;
        }

        public Criteria andGxsjNotBetween(Date value1, Date value2) {
            addCriterion("gxsj not between", value1, value2, "gxsj");
            return (Criteria) this;
        }

        public Criteria andJlztIsNull() {
            addCriterion("JLZT is null");
            return (Criteria) this;
        }

        public Criteria andJlztIsNotNull() {
            addCriterion("JLZT is not null");
            return (Criteria) this;
        }

        public Criteria andJlztEqualTo(String value) {
            addCriterion("JLZT =", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztNotEqualTo(String value) {
            addCriterion("JLZT <>", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztGreaterThan(String value) {
            addCriterion("JLZT >", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztGreaterThanOrEqualTo(String value) {
            addCriterion("JLZT >=", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztLessThan(String value) {
            addCriterion("JLZT <", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztLessThanOrEqualTo(String value) {
            addCriterion("JLZT <=", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztLike(String value) {
            addCriterion("JLZT like", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztNotLike(String value) {
            addCriterion("JLZT not like", value, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztIn(List<String> values) {
            addCriterion("JLZT in", values, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztNotIn(List<String> values) {
            addCriterion("JLZT not in", values, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztBetween(String value1, String value2) {
            addCriterion("JLZT between", value1, value2, "jlzt");
            return (Criteria) this;
        }

        public Criteria andJlztNotBetween(String value1, String value2) {
            addCriterion("JLZT not between", value1, value2, "jlzt");
            return (Criteria) this;
        }

        public Criteria andQsmcIsNull() {
            addCriterion("qsmc is null");
            return (Criteria) this;
        }

        public Criteria andQsmcIsNotNull() {
            addCriterion("qsmc is not null");
            return (Criteria) this;
        }

        public Criteria andQsmcEqualTo(String value) {
            addCriterion("qsmc =", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcNotEqualTo(String value) {
            addCriterion("qsmc <>", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcGreaterThan(String value) {
            addCriterion("qsmc >", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcGreaterThanOrEqualTo(String value) {
            addCriterion("qsmc >=", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcLessThan(String value) {
            addCriterion("qsmc <", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcLessThanOrEqualTo(String value) {
            addCriterion("qsmc <=", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcLike(String value) {
            addCriterion("qsmc like", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcNotLike(String value) {
            addCriterion("qsmc not like", value, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcIn(List<String> values) {
            addCriterion("qsmc in", values, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcNotIn(List<String> values) {
            addCriterion("qsmc not in", values, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcBetween(String value1, String value2) {
            addCriterion("qsmc between", value1, value2, "qsmc");
            return (Criteria) this;
        }

        public Criteria andQsmcNotBetween(String value1, String value2) {
            addCriterion("qsmc not between", value1, value2, "qsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcIsNull() {
            addCriterion("jsmc is null");
            return (Criteria) this;
        }

        public Criteria andJsmcIsNotNull() {
            addCriterion("jsmc is not null");
            return (Criteria) this;
        }

        public Criteria andJsmcEqualTo(String value) {
            addCriterion("jsmc =", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcNotEqualTo(String value) {
            addCriterion("jsmc <>", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcGreaterThan(String value) {
            addCriterion("jsmc >", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcGreaterThanOrEqualTo(String value) {
            addCriterion("jsmc >=", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcLessThan(String value) {
            addCriterion("jsmc <", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcLessThanOrEqualTo(String value) {
            addCriterion("jsmc <=", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcLike(String value) {
            addCriterion("jsmc like", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcNotLike(String value) {
            addCriterion("jsmc not like", value, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcIn(List<String> values) {
            addCriterion("jsmc in", values, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcNotIn(List<String> values) {
            addCriterion("jsmc not in", values, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcBetween(String value1, String value2) {
            addCriterion("jsmc between", value1, value2, "jsmc");
            return (Criteria) this;
        }

        public Criteria andJsmcNotBetween(String value1, String value2) {
            addCriterion("jsmc not between", value1, value2, "jsmc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcIsNull() {
            addCriterion("XZQHXXLC is null");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcIsNotNull() {
            addCriterion("XZQHXXLC is not null");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcEqualTo(String value) {
            addCriterion("XZQHXXLC =", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcNotEqualTo(String value) {
            addCriterion("XZQHXXLC <>", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcGreaterThan(String value) {
            addCriterion("XZQHXXLC >", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcGreaterThanOrEqualTo(String value) {
            addCriterion("XZQHXXLC >=", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcLessThan(String value) {
            addCriterion("XZQHXXLC <", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcLessThanOrEqualTo(String value) {
            addCriterion("XZQHXXLC <=", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcLike(String value) {
            addCriterion("XZQHXXLC like", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcNotLike(String value) {
            addCriterion("XZQHXXLC not like", value, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcIn(List<String> values) {
            addCriterion("XZQHXXLC in", values, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcNotIn(List<String> values) {
            addCriterion("XZQHXXLC not in", values, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcBetween(String value1, String value2) {
            addCriterion("XZQHXXLC between", value1, value2, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andXzqhxxlcNotBetween(String value1, String value2) {
            addCriterion("XZQHXXLC not between", value1, value2, "xzqhxxlc");
            return (Criteria) this;
        }

        public Criteria andZyglssIsNull() {
            addCriterion("ZYGLSS is null");
            return (Criteria) this;
        }

        public Criteria andZyglssIsNotNull() {
            addCriterion("ZYGLSS is not null");
            return (Criteria) this;
        }

        public Criteria andZyglssEqualTo(String value) {
            addCriterion("ZYGLSS =", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssNotEqualTo(String value) {
            addCriterion("ZYGLSS <>", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssGreaterThan(String value) {
            addCriterion("ZYGLSS >", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssGreaterThanOrEqualTo(String value) {
            addCriterion("ZYGLSS >=", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssLessThan(String value) {
            addCriterion("ZYGLSS <", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssLessThanOrEqualTo(String value) {
            addCriterion("ZYGLSS <=", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssLike(String value) {
            addCriterion("ZYGLSS like", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssNotLike(String value) {
            addCriterion("ZYGLSS not like", value, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssIn(List<String> values) {
            addCriterion("ZYGLSS in", values, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssNotIn(List<String> values) {
            addCriterion("ZYGLSS not in", values, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssBetween(String value1, String value2) {
            addCriterion("ZYGLSS between", value1, value2, "zyglss");
            return (Criteria) this;
        }

        public Criteria andZyglssNotBetween(String value1, String value2) {
            addCriterion("ZYGLSS not between", value1, value2, "zyglss");
            return (Criteria) this;
        }

        public Criteria andSsglbmIsNull() {
            addCriterion("SSGLBM is null");
            return (Criteria) this;
        }

        public Criteria andSsglbmIsNotNull() {
            addCriterion("SSGLBM is not null");
            return (Criteria) this;
        }

        public Criteria andSsglbmEqualTo(String value) {
            addCriterion("SSGLBM =", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmNotEqualTo(String value) {
            addCriterion("SSGLBM <>", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmGreaterThan(String value) {
            addCriterion("SSGLBM >", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmGreaterThanOrEqualTo(String value) {
            addCriterion("SSGLBM >=", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmLessThan(String value) {
            addCriterion("SSGLBM <", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmLessThanOrEqualTo(String value) {
            addCriterion("SSGLBM <=", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmLike(String value) {
            addCriterion("SSGLBM like", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmNotLike(String value) {
            addCriterion("SSGLBM not like", value, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmIn(List<String> values) {
            addCriterion("SSGLBM in", values, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmNotIn(List<String> values) {
            addCriterion("SSGLBM not in", values, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmBetween(String value1, String value2) {
            addCriterion("SSGLBM between", value1, value2, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andSsglbmNotBetween(String value1, String value2) {
            addCriterion("SSGLBM not between", value1, value2, "ssglbm");
            return (Criteria) this;
        }

        public Criteria andCsbjIsNull() {
            addCriterion("csbj is null");
            return (Criteria) this;
        }

        public Criteria andCsbjIsNotNull() {
            addCriterion("csbj is not null");
            return (Criteria) this;
        }

        public Criteria andCsbjEqualTo(String value) {
            addCriterion("csbj =", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjNotEqualTo(String value) {
            addCriterion("csbj <>", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjGreaterThan(String value) {
            addCriterion("csbj >", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjGreaterThanOrEqualTo(String value) {
            addCriterion("csbj >=", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjLessThan(String value) {
            addCriterion("csbj <", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjLessThanOrEqualTo(String value) {
            addCriterion("csbj <=", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjLike(String value) {
            addCriterion("csbj like", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjNotLike(String value) {
            addCriterion("csbj not like", value, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjIn(List<String> values) {
            addCriterion("csbj in", values, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjNotIn(List<String> values) {
            addCriterion("csbj not in", values, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjBetween(String value1, String value2) {
            addCriterion("csbj between", value1, value2, "csbj");
            return (Criteria) this;
        }

        public Criteria andCsbjNotBetween(String value1, String value2) {
            addCriterion("csbj not between", value1, value2, "csbj");
            return (Criteria) this;
        }

        public Criteria andDcbjIsNull() {
            addCriterion("dcbj is null");
            return (Criteria) this;
        }

        public Criteria andDcbjIsNotNull() {
            addCriterion("dcbj is not null");
            return (Criteria) this;
        }

        public Criteria andDcbjEqualTo(String value) {
            addCriterion("dcbj =", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjNotEqualTo(String value) {
            addCriterion("dcbj <>", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjGreaterThan(String value) {
            addCriterion("dcbj >", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjGreaterThanOrEqualTo(String value) {
            addCriterion("dcbj >=", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjLessThan(String value) {
            addCriterion("dcbj <", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjLessThanOrEqualTo(String value) {
            addCriterion("dcbj <=", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjLike(String value) {
            addCriterion("dcbj like", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjNotLike(String value) {
            addCriterion("dcbj not like", value, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjIn(List<String> values) {
            addCriterion("dcbj in", values, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjNotIn(List<String> values) {
            addCriterion("dcbj not in", values, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjBetween(String value1, String value2) {
            addCriterion("dcbj between", value1, value2, "dcbj");
            return (Criteria) this;
        }

        public Criteria andDcbjNotBetween(String value1, String value2) {
            addCriterion("dcbj not between", value1, value2, "dcbj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_road
     *
     * @mbg.generated do_not_delete_during_merge Thu May 30 14:54:05 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}