package cn.com.cybertech.sdly.model.po;

import java.io.Serializable;
import java.util.Date;

public class Road implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.GLBM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String glbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.DLDM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String dldm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.xzqh
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String xzqh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.dlmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String dlmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.dllx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String dllx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.GLXZDJ
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String glxzdj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.dx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String dx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.dlxx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String dlxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.lkldlx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String lkldlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.dlwdgl
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String dlwdgl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.lmjg
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String lmjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.fhsslx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String fhsslx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.qs
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String qs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.js
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String js;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.XQLC
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private Integer xqlc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.cjr
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String cjr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.cjsj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.gxsj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private Date gxsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.JLZT
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String jlzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.qsmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String qsmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.jsmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String jsmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.XZQHXXLC
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String xzqhxxlc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.ZYGLSS
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String zyglss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.SSGLBM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String ssglbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.csbj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String csbj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_road.dcbj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private String dcbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.GLBM
     *
     * @return the value of td_road.GLBM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getGlbm() {
        return glbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.GLBM
     *
     * @param glbm the value for td_road.GLBM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setGlbm(String glbm) {
        this.glbm = glbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.DLDM
     *
     * @return the value of td_road.DLDM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getDldm() {
        return dldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.DLDM
     *
     * @param dldm the value for td_road.DLDM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDldm(String dldm) {
        this.dldm = dldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.xzqh
     *
     * @return the value of td_road.xzqh
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.xzqh
     *
     * @param xzqh the value for td_road.xzqh
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.dlmc
     *
     * @return the value of td_road.dlmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getDlmc() {
        return dlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.dlmc
     *
     * @param dlmc the value for td_road.dlmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDlmc(String dlmc) {
        this.dlmc = dlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.dllx
     *
     * @return the value of td_road.dllx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getDllx() {
        return dllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.dllx
     *
     * @param dllx the value for td_road.dllx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDllx(String dllx) {
        this.dllx = dllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.GLXZDJ
     *
     * @return the value of td_road.GLXZDJ
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getGlxzdj() {
        return glxzdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.GLXZDJ
     *
     * @param glxzdj the value for td_road.GLXZDJ
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setGlxzdj(String glxzdj) {
        this.glxzdj = glxzdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.dx
     *
     * @return the value of td_road.dx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getDx() {
        return dx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.dx
     *
     * @param dx the value for td_road.dx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDx(String dx) {
        this.dx = dx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.dlxx
     *
     * @return the value of td_road.dlxx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getDlxx() {
        return dlxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.dlxx
     *
     * @param dlxx the value for td_road.dlxx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDlxx(String dlxx) {
        this.dlxx = dlxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.lkldlx
     *
     * @return the value of td_road.lkldlx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getLkldlx() {
        return lkldlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.lkldlx
     *
     * @param lkldlx the value for td_road.lkldlx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setLkldlx(String lkldlx) {
        this.lkldlx = lkldlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.dlwdgl
     *
     * @return the value of td_road.dlwdgl
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getDlwdgl() {
        return dlwdgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.dlwdgl
     *
     * @param dlwdgl the value for td_road.dlwdgl
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDlwdgl(String dlwdgl) {
        this.dlwdgl = dlwdgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.lmjg
     *
     * @return the value of td_road.lmjg
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getLmjg() {
        return lmjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.lmjg
     *
     * @param lmjg the value for td_road.lmjg
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setLmjg(String lmjg) {
        this.lmjg = lmjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.fhsslx
     *
     * @return the value of td_road.fhsslx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getFhsslx() {
        return fhsslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.fhsslx
     *
     * @param fhsslx the value for td_road.fhsslx
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setFhsslx(String fhsslx) {
        this.fhsslx = fhsslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.qs
     *
     * @return the value of td_road.qs
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getQs() {
        return qs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.qs
     *
     * @param qs the value for td_road.qs
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setQs(String qs) {
        this.qs = qs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.js
     *
     * @return the value of td_road.js
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getJs() {
        return js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.js
     *
     * @param js the value for td_road.js
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setJs(String js) {
        this.js = js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.XQLC
     *
     * @return the value of td_road.XQLC
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public Integer getXqlc() {
        return xqlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.XQLC
     *
     * @param xqlc the value for td_road.XQLC
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setXqlc(Integer xqlc) {
        this.xqlc = xqlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.cjr
     *
     * @return the value of td_road.cjr
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.cjr
     *
     * @param cjr the value for td_road.cjr
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.cjsj
     *
     * @return the value of td_road.cjsj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.cjsj
     *
     * @param cjsj the value for td_road.cjsj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.gxsj
     *
     * @return the value of td_road.gxsj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.gxsj
     *
     * @param gxsj the value for td_road.gxsj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.JLZT
     *
     * @return the value of td_road.JLZT
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getJlzt() {
        return jlzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.JLZT
     *
     * @param jlzt the value for td_road.JLZT
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setJlzt(String jlzt) {
        this.jlzt = jlzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.qsmc
     *
     * @return the value of td_road.qsmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getQsmc() {
        return qsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.qsmc
     *
     * @param qsmc the value for td_road.qsmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setQsmc(String qsmc) {
        this.qsmc = qsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.jsmc
     *
     * @return the value of td_road.jsmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getJsmc() {
        return jsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.jsmc
     *
     * @param jsmc the value for td_road.jsmc
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setJsmc(String jsmc) {
        this.jsmc = jsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.XZQHXXLC
     *
     * @return the value of td_road.XZQHXXLC
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getXzqhxxlc() {
        return xzqhxxlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.XZQHXXLC
     *
     * @param xzqhxxlc the value for td_road.XZQHXXLC
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setXzqhxxlc(String xzqhxxlc) {
        this.xzqhxxlc = xzqhxxlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.ZYGLSS
     *
     * @return the value of td_road.ZYGLSS
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getZyglss() {
        return zyglss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.ZYGLSS
     *
     * @param zyglss the value for td_road.ZYGLSS
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setZyglss(String zyglss) {
        this.zyglss = zyglss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.SSGLBM
     *
     * @return the value of td_road.SSGLBM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getSsglbm() {
        return ssglbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.SSGLBM
     *
     * @param ssglbm the value for td_road.SSGLBM
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setSsglbm(String ssglbm) {
        this.ssglbm = ssglbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.csbj
     *
     * @return the value of td_road.csbj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getCsbj() {
        return csbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.csbj
     *
     * @param csbj the value for td_road.csbj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setCsbj(String csbj) {
        this.csbj = csbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_road.dcbj
     *
     * @return the value of td_road.dcbj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public String getDcbj() {
        return dcbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_road.dcbj
     *
     * @param dcbj the value for td_road.dcbj
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    public void setDcbj(String dcbj) {
        this.dcbj = dcbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", glbm=").append(glbm);
        sb.append(", dldm=").append(dldm);
        sb.append(", xzqh=").append(xzqh);
        sb.append(", dlmc=").append(dlmc);
        sb.append(", dllx=").append(dllx);
        sb.append(", glxzdj=").append(glxzdj);
        sb.append(", dx=").append(dx);
        sb.append(", dlxx=").append(dlxx);
        sb.append(", lkldlx=").append(lkldlx);
        sb.append(", dlwdgl=").append(dlwdgl);
        sb.append(", lmjg=").append(lmjg);
        sb.append(", fhsslx=").append(fhsslx);
        sb.append(", qs=").append(qs);
        sb.append(", js=").append(js);
        sb.append(", xqlc=").append(xqlc);
        sb.append(", cjr=").append(cjr);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", gxsj=").append(gxsj);
        sb.append(", jlzt=").append(jlzt);
        sb.append(", qsmc=").append(qsmc);
        sb.append(", jsmc=").append(jsmc);
        sb.append(", xzqhxxlc=").append(xzqhxxlc);
        sb.append(", zyglss=").append(zyglss);
        sb.append(", ssglbm=").append(ssglbm);
        sb.append(", csbj=").append(csbj);
        sb.append(", dcbj=").append(dcbj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}