package cn.com.cybertech.sdly.model.po;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;

import java.io.Serializable;
import java.util.Date;

@ApiModel
public class TdWttc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.tcrq
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date tcrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.tcsj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Date tcsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.tcdd
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String tcdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.ddms
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String ddms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.tcyy
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String tcyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.bz
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.tfdd
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String tfdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.qzdw
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String qzdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.sbm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String sbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.sflx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String sflx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.hpzl
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String hpzl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.hphm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String hphm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.cllx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String cllx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.zjlx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String zjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.zjhm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.fzjg
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String fzjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.xm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.createtime
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_wttc.tczpurl
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String tczpurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.id
     *
     * @return the value of td_wttc.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.id
     *
     * @param id the value for td_wttc.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.tcrq
     *
     * @return the value of td_wttc.tcrq
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Date getTcrq() {
        return tcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.tcrq
     *
     * @param tcrq the value for td_wttc.tcrq
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setTcrq(Date tcrq) {
        this.tcrq = tcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.tcsj
     *
     * @return the value of td_wttc.tcsj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Date getTcsj() {
        return tcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.tcsj
     *
     * @param tcsj the value for td_wttc.tcsj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setTcsj(Date tcsj) {
        this.tcsj = tcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.tcdd
     *
     * @return the value of td_wttc.tcdd
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getTcdd() {
        return tcdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.tcdd
     *
     * @param tcdd the value for td_wttc.tcdd
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setTcdd(String tcdd) {
        this.tcdd = tcdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.ddms
     *
     * @return the value of td_wttc.ddms
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getDdms() {
        return ddms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.ddms
     *
     * @param ddms the value for td_wttc.ddms
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setDdms(String ddms) {
        this.ddms = ddms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.tcyy
     *
     * @return the value of td_wttc.tcyy
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getTcyy() {
        return tcyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.tcyy
     *
     * @param tcyy the value for td_wttc.tcyy
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setTcyy(String tcyy) {
        this.tcyy = tcyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.bz
     *
     * @return the value of td_wttc.bz
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.bz
     *
     * @param bz the value for td_wttc.bz
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.tfdd
     *
     * @return the value of td_wttc.tfdd
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getTfdd() {
        return tfdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.tfdd
     *
     * @param tfdd the value for td_wttc.tfdd
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setTfdd(String tfdd) {
        this.tfdd = tfdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.qzdw
     *
     * @return the value of td_wttc.qzdw
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getQzdw() {
        return qzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.qzdw
     *
     * @param qzdw the value for td_wttc.qzdw
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setQzdw(String qzdw) {
        this.qzdw = qzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.sbm
     *
     * @return the value of td_wttc.sbm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getSbm() {
        return sbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.sbm
     *
     * @param sbm the value for td_wttc.sbm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setSbm(String sbm) {
        this.sbm = sbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.sflx
     *
     * @return the value of td_wttc.sflx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getSflx() {
        return sflx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.sflx
     *
     * @param sflx the value for td_wttc.sflx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setSflx(String sflx) {
        this.sflx = sflx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.hpzl
     *
     * @return the value of td_wttc.hpzl
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.hpzl
     *
     * @param hpzl the value for td_wttc.hpzl
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.hphm
     *
     * @return the value of td_wttc.hphm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.hphm
     *
     * @param hphm the value for td_wttc.hphm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setHphm(String hphm) {
        this.hphm = hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.cllx
     *
     * @return the value of td_wttc.cllx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getCllx() {
        return cllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.cllx
     *
     * @param cllx the value for td_wttc.cllx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setCllx(String cllx) {
        this.cllx = cllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.zjlx
     *
     * @return the value of td_wttc.zjlx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getZjlx() {
        return zjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.zjlx
     *
     * @param zjlx the value for td_wttc.zjlx
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setZjlx(String zjlx) {
        this.zjlx = zjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.zjhm
     *
     * @return the value of td_wttc.zjhm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.zjhm
     *
     * @param zjhm the value for td_wttc.zjhm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.fzjg
     *
     * @return the value of td_wttc.fzjg
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.fzjg
     *
     * @param fzjg the value for td_wttc.fzjg
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.xm
     *
     * @return the value of td_wttc.xm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.xm
     *
     * @param xm the value for td_wttc.xm
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setXm(String xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.createtime
     *
     * @return the value of td_wttc.createtime
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.createtime
     *
     * @param createtime the value for td_wttc.createtime
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_wttc.tczpurl
     *
     * @return the value of td_wttc.tczpurl
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getTczpurl() {
        return tczpurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_wttc.tczpurl
     *
     * @param tczpurl the value for td_wttc.tczpurl
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setTczpurl(String tczpurl) {
        this.tczpurl = tczpurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tcrq=").append(tcrq);
        sb.append(", tcsj=").append(tcsj);
        sb.append(", tcdd=").append(tcdd);
        sb.append(", ddms=").append(ddms);
        sb.append(", tcyy=").append(tcyy);
        sb.append(", bz=").append(bz);
        sb.append(", tfdd=").append(tfdd);
        sb.append(", qzdw=").append(qzdw);
        sb.append(", sbm=").append(sbm);
        sb.append(", sflx=").append(sflx);
        sb.append(", hpzl=").append(hpzl);
        sb.append(", hphm=").append(hphm);
        sb.append(", cllx=").append(cllx);
        sb.append(", zjlx=").append(zjlx);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", fzjg=").append(fzjg);
        sb.append(", xm=").append(xm);
        sb.append(", createtime=").append(createtime);
        sb.append(", tczpurl=").append(tczpurl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}