package cn.com.cybertech.sdly.model.po;

import java.io.Serializable;

public class TpRolePermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_role_permission.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_role_permission.roleid
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_role_permission.permissionid
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Integer permissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_role_permission.id
     *
     * @return the value of tp_role_permission.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_role_permission.id
     *
     * @param id the value for tp_role_permission.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_role_permission.roleid
     *
     * @return the value of tp_role_permission.roleid
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_role_permission.roleid
     *
     * @param roleid the value for tp_role_permission.roleid
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_role_permission.permissionid
     *
     * @return the value of tp_role_permission.permissionid
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_role_permission.permissionid
     *
     * @param permissionid the value for tp_role_permission.permissionid
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleid=").append(roleid);
        sb.append(", permissionid=").append(permissionid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}