package cn.com.cybertech.sdly.model.po;

import java.io.Serializable;

public class TpRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_role.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_role.name
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_role.description
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_role.id
     *
     * @return the value of tp_role.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_role.id
     *
     * @param id the value for tp_role.id
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_role.name
     *
     * @return the value of tp_role.name
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_role.name
     *
     * @param name the value for tp_role.name
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_role.description
     *
     * @return the value of tp_role.description
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_role.description
     *
     * @param description the value for tp_role.description
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}