package cn.com.cybertech.sdly.model.po;

import javax.xml.bind.annotation.XmlEnumValue;
import java.io.Serializable;

public class TpUser implements Serializable {

    public static final TpUser NULL=new TpUser();
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.id
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.mjjh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    @XmlEnumValue("ss")
    private String mjjh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.mjxm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String mjxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.mjbm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String mjbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.sfzh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String sfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.password
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user.id
     *
     * @return the value of tp_user.id
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user.id
     *
     * @param id the value for tp_user.id
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user.mjjh
     *
     * @return the value of tp_user.mjjh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public String getMjjh() {
        return mjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user.mjjh
     *
     * @param mjjh the value for tp_user.mjjh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setMjjh(String mjjh) {
        this.mjjh = mjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user.mjxm
     *
     * @return the value of tp_user.mjxm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public String getMjxm() {
        return mjxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user.mjxm
     *
     * @param mjxm the value for tp_user.mjxm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setMjxm(String mjxm) {
        this.mjxm = mjxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user.mjbm
     *
     * @return the value of tp_user.mjbm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public String getMjbm() {
        return mjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user.mjbm
     *
     * @param mjbm the value for tp_user.mjbm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setMjbm(String mjbm) {
        this.mjbm = mjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user.sfzh
     *
     * @return the value of tp_user.sfzh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user.sfzh
     *
     * @param sfzh the value for tp_user.sfzh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user.password
     *
     * @return the value of tp_user.password
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user.password
     *
     * @param password the value for tp_user.password
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mjjh=").append(mjjh);
        sb.append(", mjxm=").append(mjxm);
        sb.append(", mjbm=").append(mjbm);
        sb.append(", sfzh=").append(sfzh);
        sb.append(", password=").append(password);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}