package com.hkd.mapper;

import com.hkd.model.po.Road;
import com.hkd.model.po.RoadExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    long countByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    int deleteByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    int insert(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    int insertSelective(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    List<Road> selectByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") Road record, @Param("example") RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_road
     *
     * @mbg.generated Thu May 30 14:54:05 CST 2019
     */
    int updateByExample(@Param("record") Road record, @Param("example") RoadExample example);
}