package com.hkd.mapper;

import com.hkd.model.po.TpPermission;
import com.hkd.model.po.TpPermissionExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TpPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    long countByExample(TpPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int deleteByExample(TpPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int insert(TpPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int insertSelective(TpPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    List<TpPermission> selectByExample(TpPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    TpPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") TpPermission record, @Param("example") TpPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByExample(@Param("record") TpPermission record, @Param("example") TpPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByPrimaryKeySelective(TpPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByPrimaryKey(TpPermission record);
}