package com.hkd.mapper;

import com.hkd.model.po.TpUserRole;
import com.hkd.model.po.TpUserRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TpUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    long countByExample(TpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int deleteByExample(TpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int insert(TpUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int insertSelective(TpUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    List<TpUserRole> selectByExample(TpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    TpUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") TpUserRole record, @Param("example") TpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByExample(@Param("record") TpUserRole record, @Param("example") TpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByPrimaryKeySelective(TpUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_role
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByPrimaryKey(TpUserRole record);
}