package com.hkd.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TdWttcExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public TdWttcExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTcrqIsNull() {
            addCriterion("tcrq is null");
            return (Criteria) this;
        }

        public Criteria andTcrqIsNotNull() {
            addCriterion("tcrq is not null");
            return (Criteria) this;
        }

        public Criteria andTcrqEqualTo(Date value) {
            addCriterionForJDBCDate("tcrq =", value, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("tcrq <>", value, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqGreaterThan(Date value) {
            addCriterionForJDBCDate("tcrq >", value, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tcrq >=", value, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqLessThan(Date value) {
            addCriterionForJDBCDate("tcrq <", value, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tcrq <=", value, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqIn(List<Date> values) {
            addCriterionForJDBCDate("tcrq in", values, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqNotIn(List<Date> values) {
            addCriterionForJDBCDate("tcrq not in", values, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tcrq between", value1, value2, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tcrq not between", value1, value2, "tcrq");
            return (Criteria) this;
        }

        public Criteria andTcsjIsNull() {
            addCriterion("tcsj is null");
            return (Criteria) this;
        }

        public Criteria andTcsjIsNotNull() {
            addCriterion("tcsj is not null");
            return (Criteria) this;
        }

        public Criteria andTcsjEqualTo(Date value) {
            addCriterion("tcsj =", value, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjNotEqualTo(Date value) {
            addCriterion("tcsj <>", value, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjGreaterThan(Date value) {
            addCriterion("tcsj >", value, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjGreaterThanOrEqualTo(Date value) {
            addCriterion("tcsj >=", value, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjLessThan(Date value) {
            addCriterion("tcsj <", value, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjLessThanOrEqualTo(Date value) {
            addCriterion("tcsj <=", value, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjIn(List<Date> values) {
            addCriterion("tcsj in", values, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjNotIn(List<Date> values) {
            addCriterion("tcsj not in", values, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjBetween(Date value1, Date value2) {
            addCriterion("tcsj between", value1, value2, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcsjNotBetween(Date value1, Date value2) {
            addCriterion("tcsj not between", value1, value2, "tcsj");
            return (Criteria) this;
        }

        public Criteria andTcddIsNull() {
            addCriterion("tcdd is null");
            return (Criteria) this;
        }

        public Criteria andTcddIsNotNull() {
            addCriterion("tcdd is not null");
            return (Criteria) this;
        }

        public Criteria andTcddEqualTo(String value) {
            addCriterion("tcdd =", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddNotEqualTo(String value) {
            addCriterion("tcdd <>", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddGreaterThan(String value) {
            addCriterion("tcdd >", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddGreaterThanOrEqualTo(String value) {
            addCriterion("tcdd >=", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddLessThan(String value) {
            addCriterion("tcdd <", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddLessThanOrEqualTo(String value) {
            addCriterion("tcdd <=", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddLike(String value) {
            addCriterion("tcdd like", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddNotLike(String value) {
            addCriterion("tcdd not like", value, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddIn(List<String> values) {
            addCriterion("tcdd in", values, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddNotIn(List<String> values) {
            addCriterion("tcdd not in", values, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddBetween(String value1, String value2) {
            addCriterion("tcdd between", value1, value2, "tcdd");
            return (Criteria) this;
        }

        public Criteria andTcddNotBetween(String value1, String value2) {
            addCriterion("tcdd not between", value1, value2, "tcdd");
            return (Criteria) this;
        }

        public Criteria andDdmsIsNull() {
            addCriterion("ddms is null");
            return (Criteria) this;
        }

        public Criteria andDdmsIsNotNull() {
            addCriterion("ddms is not null");
            return (Criteria) this;
        }

        public Criteria andDdmsEqualTo(String value) {
            addCriterion("ddms =", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsNotEqualTo(String value) {
            addCriterion("ddms <>", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsGreaterThan(String value) {
            addCriterion("ddms >", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsGreaterThanOrEqualTo(String value) {
            addCriterion("ddms >=", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsLessThan(String value) {
            addCriterion("ddms <", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsLessThanOrEqualTo(String value) {
            addCriterion("ddms <=", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsLike(String value) {
            addCriterion("ddms like", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsNotLike(String value) {
            addCriterion("ddms not like", value, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsIn(List<String> values) {
            addCriterion("ddms in", values, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsNotIn(List<String> values) {
            addCriterion("ddms not in", values, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsBetween(String value1, String value2) {
            addCriterion("ddms between", value1, value2, "ddms");
            return (Criteria) this;
        }

        public Criteria andDdmsNotBetween(String value1, String value2) {
            addCriterion("ddms not between", value1, value2, "ddms");
            return (Criteria) this;
        }

        public Criteria andTcyyIsNull() {
            addCriterion("tcyy is null");
            return (Criteria) this;
        }

        public Criteria andTcyyIsNotNull() {
            addCriterion("tcyy is not null");
            return (Criteria) this;
        }

        public Criteria andTcyyEqualTo(String value) {
            addCriterion("tcyy =", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyNotEqualTo(String value) {
            addCriterion("tcyy <>", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyGreaterThan(String value) {
            addCriterion("tcyy >", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyGreaterThanOrEqualTo(String value) {
            addCriterion("tcyy >=", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyLessThan(String value) {
            addCriterion("tcyy <", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyLessThanOrEqualTo(String value) {
            addCriterion("tcyy <=", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyLike(String value) {
            addCriterion("tcyy like", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyNotLike(String value) {
            addCriterion("tcyy not like", value, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyIn(List<String> values) {
            addCriterion("tcyy in", values, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyNotIn(List<String> values) {
            addCriterion("tcyy not in", values, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyBetween(String value1, String value2) {
            addCriterion("tcyy between", value1, value2, "tcyy");
            return (Criteria) this;
        }

        public Criteria andTcyyNotBetween(String value1, String value2) {
            addCriterion("tcyy not between", value1, value2, "tcyy");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andTfddIsNull() {
            addCriterion("tfdd is null");
            return (Criteria) this;
        }

        public Criteria andTfddIsNotNull() {
            addCriterion("tfdd is not null");
            return (Criteria) this;
        }

        public Criteria andTfddEqualTo(String value) {
            addCriterion("tfdd =", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddNotEqualTo(String value) {
            addCriterion("tfdd <>", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddGreaterThan(String value) {
            addCriterion("tfdd >", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddGreaterThanOrEqualTo(String value) {
            addCriterion("tfdd >=", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddLessThan(String value) {
            addCriterion("tfdd <", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddLessThanOrEqualTo(String value) {
            addCriterion("tfdd <=", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddLike(String value) {
            addCriterion("tfdd like", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddNotLike(String value) {
            addCriterion("tfdd not like", value, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddIn(List<String> values) {
            addCriterion("tfdd in", values, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddNotIn(List<String> values) {
            addCriterion("tfdd not in", values, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddBetween(String value1, String value2) {
            addCriterion("tfdd between", value1, value2, "tfdd");
            return (Criteria) this;
        }

        public Criteria andTfddNotBetween(String value1, String value2) {
            addCriterion("tfdd not between", value1, value2, "tfdd");
            return (Criteria) this;
        }

        public Criteria andQzdwIsNull() {
            addCriterion("qzdw is null");
            return (Criteria) this;
        }

        public Criteria andQzdwIsNotNull() {
            addCriterion("qzdw is not null");
            return (Criteria) this;
        }

        public Criteria andQzdwEqualTo(String value) {
            addCriterion("qzdw =", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwNotEqualTo(String value) {
            addCriterion("qzdw <>", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwGreaterThan(String value) {
            addCriterion("qzdw >", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwGreaterThanOrEqualTo(String value) {
            addCriterion("qzdw >=", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwLessThan(String value) {
            addCriterion("qzdw <", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwLessThanOrEqualTo(String value) {
            addCriterion("qzdw <=", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwLike(String value) {
            addCriterion("qzdw like", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwNotLike(String value) {
            addCriterion("qzdw not like", value, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwIn(List<String> values) {
            addCriterion("qzdw in", values, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwNotIn(List<String> values) {
            addCriterion("qzdw not in", values, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwBetween(String value1, String value2) {
            addCriterion("qzdw between", value1, value2, "qzdw");
            return (Criteria) this;
        }

        public Criteria andQzdwNotBetween(String value1, String value2) {
            addCriterion("qzdw not between", value1, value2, "qzdw");
            return (Criteria) this;
        }

        public Criteria andSbmIsNull() {
            addCriterion("sbm is null");
            return (Criteria) this;
        }

        public Criteria andSbmIsNotNull() {
            addCriterion("sbm is not null");
            return (Criteria) this;
        }

        public Criteria andSbmEqualTo(String value) {
            addCriterion("sbm =", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmNotEqualTo(String value) {
            addCriterion("sbm <>", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmGreaterThan(String value) {
            addCriterion("sbm >", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmGreaterThanOrEqualTo(String value) {
            addCriterion("sbm >=", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmLessThan(String value) {
            addCriterion("sbm <", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmLessThanOrEqualTo(String value) {
            addCriterion("sbm <=", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmLike(String value) {
            addCriterion("sbm like", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmNotLike(String value) {
            addCriterion("sbm not like", value, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmIn(List<String> values) {
            addCriterion("sbm in", values, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmNotIn(List<String> values) {
            addCriterion("sbm not in", values, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmBetween(String value1, String value2) {
            addCriterion("sbm between", value1, value2, "sbm");
            return (Criteria) this;
        }

        public Criteria andSbmNotBetween(String value1, String value2) {
            addCriterion("sbm not between", value1, value2, "sbm");
            return (Criteria) this;
        }

        public Criteria andSflxIsNull() {
            addCriterion("sflx is null");
            return (Criteria) this;
        }

        public Criteria andSflxIsNotNull() {
            addCriterion("sflx is not null");
            return (Criteria) this;
        }

        public Criteria andSflxEqualTo(String value) {
            addCriterion("sflx =", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotEqualTo(String value) {
            addCriterion("sflx <>", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxGreaterThan(String value) {
            addCriterion("sflx >", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxGreaterThanOrEqualTo(String value) {
            addCriterion("sflx >=", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxLessThan(String value) {
            addCriterion("sflx <", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxLessThanOrEqualTo(String value) {
            addCriterion("sflx <=", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxLike(String value) {
            addCriterion("sflx like", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotLike(String value) {
            addCriterion("sflx not like", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxIn(List<String> values) {
            addCriterion("sflx in", values, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotIn(List<String> values) {
            addCriterion("sflx not in", values, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxBetween(String value1, String value2) {
            addCriterion("sflx between", value1, value2, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotBetween(String value1, String value2) {
            addCriterion("sflx not between", value1, value2, "sflx");
            return (Criteria) this;
        }

        public Criteria andHpzlIsNull() {
            addCriterion("hpzl is null");
            return (Criteria) this;
        }

        public Criteria andHpzlIsNotNull() {
            addCriterion("hpzl is not null");
            return (Criteria) this;
        }

        public Criteria andHpzlEqualTo(String value) {
            addCriterion("hpzl =", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlNotEqualTo(String value) {
            addCriterion("hpzl <>", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlGreaterThan(String value) {
            addCriterion("hpzl >", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlGreaterThanOrEqualTo(String value) {
            addCriterion("hpzl >=", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlLessThan(String value) {
            addCriterion("hpzl <", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlLessThanOrEqualTo(String value) {
            addCriterion("hpzl <=", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlLike(String value) {
            addCriterion("hpzl like", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlNotLike(String value) {
            addCriterion("hpzl not like", value, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlIn(List<String> values) {
            addCriterion("hpzl in", values, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlNotIn(List<String> values) {
            addCriterion("hpzl not in", values, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlBetween(String value1, String value2) {
            addCriterion("hpzl between", value1, value2, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHpzlNotBetween(String value1, String value2) {
            addCriterion("hpzl not between", value1, value2, "hpzl");
            return (Criteria) this;
        }

        public Criteria andHphmIsNull() {
            addCriterion("hphm is null");
            return (Criteria) this;
        }

        public Criteria andHphmIsNotNull() {
            addCriterion("hphm is not null");
            return (Criteria) this;
        }

        public Criteria andHphmEqualTo(String value) {
            addCriterion("hphm =", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotEqualTo(String value) {
            addCriterion("hphm <>", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmGreaterThan(String value) {
            addCriterion("hphm >", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmGreaterThanOrEqualTo(String value) {
            addCriterion("hphm >=", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmLessThan(String value) {
            addCriterion("hphm <", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmLessThanOrEqualTo(String value) {
            addCriterion("hphm <=", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmLike(String value) {
            addCriterion("hphm like", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotLike(String value) {
            addCriterion("hphm not like", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmIn(List<String> values) {
            addCriterion("hphm in", values, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotIn(List<String> values) {
            addCriterion("hphm not in", values, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmBetween(String value1, String value2) {
            addCriterion("hphm between", value1, value2, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotBetween(String value1, String value2) {
            addCriterion("hphm not between", value1, value2, "hphm");
            return (Criteria) this;
        }

        public Criteria andCllxIsNull() {
            addCriterion("cllx is null");
            return (Criteria) this;
        }

        public Criteria andCllxIsNotNull() {
            addCriterion("cllx is not null");
            return (Criteria) this;
        }

        public Criteria andCllxEqualTo(String value) {
            addCriterion("cllx =", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxNotEqualTo(String value) {
            addCriterion("cllx <>", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxGreaterThan(String value) {
            addCriterion("cllx >", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxGreaterThanOrEqualTo(String value) {
            addCriterion("cllx >=", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxLessThan(String value) {
            addCriterion("cllx <", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxLessThanOrEqualTo(String value) {
            addCriterion("cllx <=", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxLike(String value) {
            addCriterion("cllx like", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxNotLike(String value) {
            addCriterion("cllx not like", value, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxIn(List<String> values) {
            addCriterion("cllx in", values, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxNotIn(List<String> values) {
            addCriterion("cllx not in", values, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxBetween(String value1, String value2) {
            addCriterion("cllx between", value1, value2, "cllx");
            return (Criteria) this;
        }

        public Criteria andCllxNotBetween(String value1, String value2) {
            addCriterion("cllx not between", value1, value2, "cllx");
            return (Criteria) this;
        }

        public Criteria andZjlxIsNull() {
            addCriterion("zjlx is null");
            return (Criteria) this;
        }

        public Criteria andZjlxIsNotNull() {
            addCriterion("zjlx is not null");
            return (Criteria) this;
        }

        public Criteria andZjlxEqualTo(String value) {
            addCriterion("zjlx =", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxNotEqualTo(String value) {
            addCriterion("zjlx <>", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxGreaterThan(String value) {
            addCriterion("zjlx >", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxGreaterThanOrEqualTo(String value) {
            addCriterion("zjlx >=", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxLessThan(String value) {
            addCriterion("zjlx <", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxLessThanOrEqualTo(String value) {
            addCriterion("zjlx <=", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxLike(String value) {
            addCriterion("zjlx like", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxNotLike(String value) {
            addCriterion("zjlx not like", value, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxIn(List<String> values) {
            addCriterion("zjlx in", values, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxNotIn(List<String> values) {
            addCriterion("zjlx not in", values, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxBetween(String value1, String value2) {
            addCriterion("zjlx between", value1, value2, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjlxNotBetween(String value1, String value2) {
            addCriterion("zjlx not between", value1, value2, "zjlx");
            return (Criteria) this;
        }

        public Criteria andZjhmIsNull() {
            addCriterion("zjhm is null");
            return (Criteria) this;
        }

        public Criteria andZjhmIsNotNull() {
            addCriterion("zjhm is not null");
            return (Criteria) this;
        }

        public Criteria andZjhmEqualTo(String value) {
            addCriterion("zjhm =", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmNotEqualTo(String value) {
            addCriterion("zjhm <>", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmGreaterThan(String value) {
            addCriterion("zjhm >", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmGreaterThanOrEqualTo(String value) {
            addCriterion("zjhm >=", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmLessThan(String value) {
            addCriterion("zjhm <", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmLessThanOrEqualTo(String value) {
            addCriterion("zjhm <=", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmLike(String value) {
            addCriterion("zjhm like", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmNotLike(String value) {
            addCriterion("zjhm not like", value, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmIn(List<String> values) {
            addCriterion("zjhm in", values, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmNotIn(List<String> values) {
            addCriterion("zjhm not in", values, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmBetween(String value1, String value2) {
            addCriterion("zjhm between", value1, value2, "zjhm");
            return (Criteria) this;
        }

        public Criteria andZjhmNotBetween(String value1, String value2) {
            addCriterion("zjhm not between", value1, value2, "zjhm");
            return (Criteria) this;
        }

        public Criteria andFzjgIsNull() {
            addCriterion("fzjg is null");
            return (Criteria) this;
        }

        public Criteria andFzjgIsNotNull() {
            addCriterion("fzjg is not null");
            return (Criteria) this;
        }

        public Criteria andFzjgEqualTo(String value) {
            addCriterion("fzjg =", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgNotEqualTo(String value) {
            addCriterion("fzjg <>", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgGreaterThan(String value) {
            addCriterion("fzjg >", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgGreaterThanOrEqualTo(String value) {
            addCriterion("fzjg >=", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgLessThan(String value) {
            addCriterion("fzjg <", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgLessThanOrEqualTo(String value) {
            addCriterion("fzjg <=", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgLike(String value) {
            addCriterion("fzjg like", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgNotLike(String value) {
            addCriterion("fzjg not like", value, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgIn(List<String> values) {
            addCriterion("fzjg in", values, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgNotIn(List<String> values) {
            addCriterion("fzjg not in", values, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgBetween(String value1, String value2) {
            addCriterion("fzjg between", value1, value2, "fzjg");
            return (Criteria) this;
        }

        public Criteria andFzjgNotBetween(String value1, String value2) {
            addCriterion("fzjg not between", value1, value2, "fzjg");
            return (Criteria) this;
        }

        public Criteria andXmIsNull() {
            addCriterion("xm is null");
            return (Criteria) this;
        }

        public Criteria andXmIsNotNull() {
            addCriterion("xm is not null");
            return (Criteria) this;
        }

        public Criteria andXmEqualTo(String value) {
            addCriterion("xm =", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotEqualTo(String value) {
            addCriterion("xm <>", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThan(String value) {
            addCriterion("xm >", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThanOrEqualTo(String value) {
            addCriterion("xm >=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThan(String value) {
            addCriterion("xm <", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThanOrEqualTo(String value) {
            addCriterion("xm <=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLike(String value) {
            addCriterion("xm like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotLike(String value) {
            addCriterion("xm not like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmIn(List<String> values) {
            addCriterion("xm in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotIn(List<String> values) {
            addCriterion("xm not in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmBetween(String value1, String value2) {
            addCriterion("xm between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotBetween(String value1, String value2) {
            addCriterion("xm not between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andTczpurlIsNull() {
            addCriterion("tczpurl is null");
            return (Criteria) this;
        }

        public Criteria andTczpurlIsNotNull() {
            addCriterion("tczpurl is not null");
            return (Criteria) this;
        }

        public Criteria andTczpurlEqualTo(String value) {
            addCriterion("tczpurl =", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlNotEqualTo(String value) {
            addCriterion("tczpurl <>", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlGreaterThan(String value) {
            addCriterion("tczpurl >", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlGreaterThanOrEqualTo(String value) {
            addCriterion("tczpurl >=", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlLessThan(String value) {
            addCriterion("tczpurl <", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlLessThanOrEqualTo(String value) {
            addCriterion("tczpurl <=", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlLike(String value) {
            addCriterion("tczpurl like", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlNotLike(String value) {
            addCriterion("tczpurl not like", value, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlIn(List<String> values) {
            addCriterion("tczpurl in", values, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlNotIn(List<String> values) {
            addCriterion("tczpurl not in", values, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlBetween(String value1, String value2) {
            addCriterion("tczpurl between", value1, value2, "tczpurl");
            return (Criteria) this;
        }

        public Criteria andTczpurlNotBetween(String value1, String value2) {
            addCriterion("tczpurl not between", value1, value2, "tczpurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_wttc
     *
     * @mbg.generated do_not_delete_during_merge Mon May 27 16:24:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_wttc
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}