package com.hkd.model.po;

import java.io.Serializable;
import java.util.Date;

public class TpDepart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jgbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JGMC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jgmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JGJC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jgjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.SJJGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String sjjgbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.BMJB
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String bmjb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JKYH
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jkyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.SSJG
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String ssjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.FYJG
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String fyjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.DDQZ
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String ddqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.PXYJ
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String pxyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.XZCFJGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String xzcfjgbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.WZCLBMMC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String wzclbmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.SGCLD
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String sgcld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JDSTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jdstt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JDSTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jdstt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JDSTT3
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jdstt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.JDSTT4
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String jdstt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.ID
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.SADJBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String sadjbtt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.GZBLTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String gzbltt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.GZBLTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String gzbltt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.QZCSSPBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String qzcsspbtt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.XZCFSPBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String xzcfspbtt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.CFJDSTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String cfjdstt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.CFJDSTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String cfjdstt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.TZDWTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String tzdwtt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.rksj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Date rksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.updatetime
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_depart.zsbj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private String zsbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JGBM
     *
     * @return the value of tp_depart.JGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJgbm() {
        return jgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JGBM
     *
     * @param jgbm the value for tp_depart.JGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJgbm(String jgbm) {
        this.jgbm = jgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JGMC
     *
     * @return the value of tp_depart.JGMC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JGMC
     *
     * @param jgmc the value for tp_depart.JGMC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JGJC
     *
     * @return the value of tp_depart.JGJC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJgjc() {
        return jgjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JGJC
     *
     * @param jgjc the value for tp_depart.JGJC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJgjc(String jgjc) {
        this.jgjc = jgjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.SJJGBM
     *
     * @return the value of tp_depart.SJJGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getSjjgbm() {
        return sjjgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.SJJGBM
     *
     * @param sjjgbm the value for tp_depart.SJJGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setSjjgbm(String sjjgbm) {
        this.sjjgbm = sjjgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.BMJB
     *
     * @return the value of tp_depart.BMJB
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getBmjb() {
        return bmjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.BMJB
     *
     * @param bmjb the value for tp_depart.BMJB
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setBmjb(String bmjb) {
        this.bmjb = bmjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JKYH
     *
     * @return the value of tp_depart.JKYH
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJkyh() {
        return jkyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JKYH
     *
     * @param jkyh the value for tp_depart.JKYH
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJkyh(String jkyh) {
        this.jkyh = jkyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.SSJG
     *
     * @return the value of tp_depart.SSJG
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getSsjg() {
        return ssjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.SSJG
     *
     * @param ssjg the value for tp_depart.SSJG
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setSsjg(String ssjg) {
        this.ssjg = ssjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.FYJG
     *
     * @return the value of tp_depart.FYJG
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getFyjg() {
        return fyjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.FYJG
     *
     * @param fyjg the value for tp_depart.FYJG
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setFyjg(String fyjg) {
        this.fyjg = fyjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.DDQZ
     *
     * @return the value of tp_depart.DDQZ
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getDdqz() {
        return ddqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.DDQZ
     *
     * @param ddqz the value for tp_depart.DDQZ
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setDdqz(String ddqz) {
        this.ddqz = ddqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.PXYJ
     *
     * @return the value of tp_depart.PXYJ
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getPxyj() {
        return pxyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.PXYJ
     *
     * @param pxyj the value for tp_depart.PXYJ
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setPxyj(String pxyj) {
        this.pxyj = pxyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.XZCFJGBM
     *
     * @return the value of tp_depart.XZCFJGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getXzcfjgbm() {
        return xzcfjgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.XZCFJGBM
     *
     * @param xzcfjgbm the value for tp_depart.XZCFJGBM
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setXzcfjgbm(String xzcfjgbm) {
        this.xzcfjgbm = xzcfjgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.WZCLBMMC
     *
     * @return the value of tp_depart.WZCLBMMC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getWzclbmmc() {
        return wzclbmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.WZCLBMMC
     *
     * @param wzclbmmc the value for tp_depart.WZCLBMMC
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setWzclbmmc(String wzclbmmc) {
        this.wzclbmmc = wzclbmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.SGCLD
     *
     * @return the value of tp_depart.SGCLD
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getSgcld() {
        return sgcld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.SGCLD
     *
     * @param sgcld the value for tp_depart.SGCLD
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setSgcld(String sgcld) {
        this.sgcld = sgcld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JDSTT1
     *
     * @return the value of tp_depart.JDSTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJdstt1() {
        return jdstt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JDSTT1
     *
     * @param jdstt1 the value for tp_depart.JDSTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJdstt1(String jdstt1) {
        this.jdstt1 = jdstt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JDSTT2
     *
     * @return the value of tp_depart.JDSTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJdstt2() {
        return jdstt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JDSTT2
     *
     * @param jdstt2 the value for tp_depart.JDSTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJdstt2(String jdstt2) {
        this.jdstt2 = jdstt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JDSTT3
     *
     * @return the value of tp_depart.JDSTT3
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJdstt3() {
        return jdstt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JDSTT3
     *
     * @param jdstt3 the value for tp_depart.JDSTT3
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJdstt3(String jdstt3) {
        this.jdstt3 = jdstt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.JDSTT4
     *
     * @return the value of tp_depart.JDSTT4
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getJdstt4() {
        return jdstt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.JDSTT4
     *
     * @param jdstt4 the value for tp_depart.JDSTT4
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setJdstt4(String jdstt4) {
        this.jdstt4 = jdstt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.ID
     *
     * @return the value of tp_depart.ID
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.ID
     *
     * @param id the value for tp_depart.ID
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.SADJBTT
     *
     * @return the value of tp_depart.SADJBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getSadjbtt() {
        return sadjbtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.SADJBTT
     *
     * @param sadjbtt the value for tp_depart.SADJBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setSadjbtt(String sadjbtt) {
        this.sadjbtt = sadjbtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.GZBLTT1
     *
     * @return the value of tp_depart.GZBLTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getGzbltt1() {
        return gzbltt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.GZBLTT1
     *
     * @param gzbltt1 the value for tp_depart.GZBLTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setGzbltt1(String gzbltt1) {
        this.gzbltt1 = gzbltt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.GZBLTT2
     *
     * @return the value of tp_depart.GZBLTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getGzbltt2() {
        return gzbltt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.GZBLTT2
     *
     * @param gzbltt2 the value for tp_depart.GZBLTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setGzbltt2(String gzbltt2) {
        this.gzbltt2 = gzbltt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.QZCSSPBTT
     *
     * @return the value of tp_depart.QZCSSPBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getQzcsspbtt() {
        return qzcsspbtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.QZCSSPBTT
     *
     * @param qzcsspbtt the value for tp_depart.QZCSSPBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setQzcsspbtt(String qzcsspbtt) {
        this.qzcsspbtt = qzcsspbtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.XZCFSPBTT
     *
     * @return the value of tp_depart.XZCFSPBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getXzcfspbtt() {
        return xzcfspbtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.XZCFSPBTT
     *
     * @param xzcfspbtt the value for tp_depart.XZCFSPBTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setXzcfspbtt(String xzcfspbtt) {
        this.xzcfspbtt = xzcfspbtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.CFJDSTT1
     *
     * @return the value of tp_depart.CFJDSTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getCfjdstt1() {
        return cfjdstt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.CFJDSTT1
     *
     * @param cfjdstt1 the value for tp_depart.CFJDSTT1
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setCfjdstt1(String cfjdstt1) {
        this.cfjdstt1 = cfjdstt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.CFJDSTT2
     *
     * @return the value of tp_depart.CFJDSTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getCfjdstt2() {
        return cfjdstt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.CFJDSTT2
     *
     * @param cfjdstt2 the value for tp_depart.CFJDSTT2
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setCfjdstt2(String cfjdstt2) {
        this.cfjdstt2 = cfjdstt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.TZDWTT
     *
     * @return the value of tp_depart.TZDWTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getTzdwtt() {
        return tzdwtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.TZDWTT
     *
     * @param tzdwtt the value for tp_depart.TZDWTT
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setTzdwtt(String tzdwtt) {
        this.tzdwtt = tzdwtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.rksj
     *
     * @return the value of tp_depart.rksj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Date getRksj() {
        return rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.rksj
     *
     * @param rksj the value for tp_depart.rksj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setRksj(Date rksj) {
        this.rksj = rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.updatetime
     *
     * @return the value of tp_depart.updatetime
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.updatetime
     *
     * @param updatetime the value for tp_depart.updatetime
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_depart.zsbj
     *
     * @return the value of tp_depart.zsbj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getZsbj() {
        return zsbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_depart.zsbj
     *
     * @param zsbj the value for tp_depart.zsbj
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setZsbj(String zsbj) {
        this.zsbj = zsbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jgbm=").append(jgbm);
        sb.append(", jgmc=").append(jgmc);
        sb.append(", jgjc=").append(jgjc);
        sb.append(", sjjgbm=").append(sjjgbm);
        sb.append(", bmjb=").append(bmjb);
        sb.append(", jkyh=").append(jkyh);
        sb.append(", ssjg=").append(ssjg);
        sb.append(", fyjg=").append(fyjg);
        sb.append(", ddqz=").append(ddqz);
        sb.append(", pxyj=").append(pxyj);
        sb.append(", xzcfjgbm=").append(xzcfjgbm);
        sb.append(", wzclbmmc=").append(wzclbmmc);
        sb.append(", sgcld=").append(sgcld);
        sb.append(", jdstt1=").append(jdstt1);
        sb.append(", jdstt2=").append(jdstt2);
        sb.append(", jdstt3=").append(jdstt3);
        sb.append(", jdstt4=").append(jdstt4);
        sb.append(", id=").append(id);
        sb.append(", sadjbtt=").append(sadjbtt);
        sb.append(", gzbltt1=").append(gzbltt1);
        sb.append(", gzbltt2=").append(gzbltt2);
        sb.append(", qzcsspbtt=").append(qzcsspbtt);
        sb.append(", xzcfspbtt=").append(xzcfspbtt);
        sb.append(", cfjdstt1=").append(cfjdstt1);
        sb.append(", cfjdstt2=").append(cfjdstt2);
        sb.append(", tzdwtt=").append(tzdwtt);
        sb.append(", rksj=").append(rksj);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", zsbj=").append(zsbj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}