package com.hkd.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TpDepartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public TpDepartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJgbmIsNull() {
            addCriterion("JGBM is null");
            return (Criteria) this;
        }

        public Criteria andJgbmIsNotNull() {
            addCriterion("JGBM is not null");
            return (Criteria) this;
        }

        public Criteria andJgbmEqualTo(String value) {
            addCriterion("JGBM =", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmNotEqualTo(String value) {
            addCriterion("JGBM <>", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmGreaterThan(String value) {
            addCriterion("JGBM >", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmGreaterThanOrEqualTo(String value) {
            addCriterion("JGBM >=", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmLessThan(String value) {
            addCriterion("JGBM <", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmLessThanOrEqualTo(String value) {
            addCriterion("JGBM <=", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmLike(String value) {
            addCriterion("JGBM like", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmNotLike(String value) {
            addCriterion("JGBM not like", value, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmIn(List<String> values) {
            addCriterion("JGBM in", values, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmNotIn(List<String> values) {
            addCriterion("JGBM not in", values, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmBetween(String value1, String value2) {
            addCriterion("JGBM between", value1, value2, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgbmNotBetween(String value1, String value2) {
            addCriterion("JGBM not between", value1, value2, "jgbm");
            return (Criteria) this;
        }

        public Criteria andJgmcIsNull() {
            addCriterion("JGMC is null");
            return (Criteria) this;
        }

        public Criteria andJgmcIsNotNull() {
            addCriterion("JGMC is not null");
            return (Criteria) this;
        }

        public Criteria andJgmcEqualTo(String value) {
            addCriterion("JGMC =", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcNotEqualTo(String value) {
            addCriterion("JGMC <>", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcGreaterThan(String value) {
            addCriterion("JGMC >", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcGreaterThanOrEqualTo(String value) {
            addCriterion("JGMC >=", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcLessThan(String value) {
            addCriterion("JGMC <", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcLessThanOrEqualTo(String value) {
            addCriterion("JGMC <=", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcLike(String value) {
            addCriterion("JGMC like", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcNotLike(String value) {
            addCriterion("JGMC not like", value, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcIn(List<String> values) {
            addCriterion("JGMC in", values, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcNotIn(List<String> values) {
            addCriterion("JGMC not in", values, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcBetween(String value1, String value2) {
            addCriterion("JGMC between", value1, value2, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgmcNotBetween(String value1, String value2) {
            addCriterion("JGMC not between", value1, value2, "jgmc");
            return (Criteria) this;
        }

        public Criteria andJgjcIsNull() {
            addCriterion("JGJC is null");
            return (Criteria) this;
        }

        public Criteria andJgjcIsNotNull() {
            addCriterion("JGJC is not null");
            return (Criteria) this;
        }

        public Criteria andJgjcEqualTo(String value) {
            addCriterion("JGJC =", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcNotEqualTo(String value) {
            addCriterion("JGJC <>", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcGreaterThan(String value) {
            addCriterion("JGJC >", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcGreaterThanOrEqualTo(String value) {
            addCriterion("JGJC >=", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcLessThan(String value) {
            addCriterion("JGJC <", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcLessThanOrEqualTo(String value) {
            addCriterion("JGJC <=", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcLike(String value) {
            addCriterion("JGJC like", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcNotLike(String value) {
            addCriterion("JGJC not like", value, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcIn(List<String> values) {
            addCriterion("JGJC in", values, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcNotIn(List<String> values) {
            addCriterion("JGJC not in", values, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcBetween(String value1, String value2) {
            addCriterion("JGJC between", value1, value2, "jgjc");
            return (Criteria) this;
        }

        public Criteria andJgjcNotBetween(String value1, String value2) {
            addCriterion("JGJC not between", value1, value2, "jgjc");
            return (Criteria) this;
        }

        public Criteria andSjjgbmIsNull() {
            addCriterion("SJJGBM is null");
            return (Criteria) this;
        }

        public Criteria andSjjgbmIsNotNull() {
            addCriterion("SJJGBM is not null");
            return (Criteria) this;
        }

        public Criteria andSjjgbmEqualTo(String value) {
            addCriterion("SJJGBM =", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmNotEqualTo(String value) {
            addCriterion("SJJGBM <>", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmGreaterThan(String value) {
            addCriterion("SJJGBM >", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmGreaterThanOrEqualTo(String value) {
            addCriterion("SJJGBM >=", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmLessThan(String value) {
            addCriterion("SJJGBM <", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmLessThanOrEqualTo(String value) {
            addCriterion("SJJGBM <=", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmLike(String value) {
            addCriterion("SJJGBM like", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmNotLike(String value) {
            addCriterion("SJJGBM not like", value, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmIn(List<String> values) {
            addCriterion("SJJGBM in", values, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmNotIn(List<String> values) {
            addCriterion("SJJGBM not in", values, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmBetween(String value1, String value2) {
            addCriterion("SJJGBM between", value1, value2, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andSjjgbmNotBetween(String value1, String value2) {
            addCriterion("SJJGBM not between", value1, value2, "sjjgbm");
            return (Criteria) this;
        }

        public Criteria andBmjbIsNull() {
            addCriterion("BMJB is null");
            return (Criteria) this;
        }

        public Criteria andBmjbIsNotNull() {
            addCriterion("BMJB is not null");
            return (Criteria) this;
        }

        public Criteria andBmjbEqualTo(String value) {
            addCriterion("BMJB =", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbNotEqualTo(String value) {
            addCriterion("BMJB <>", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbGreaterThan(String value) {
            addCriterion("BMJB >", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbGreaterThanOrEqualTo(String value) {
            addCriterion("BMJB >=", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbLessThan(String value) {
            addCriterion("BMJB <", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbLessThanOrEqualTo(String value) {
            addCriterion("BMJB <=", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbLike(String value) {
            addCriterion("BMJB like", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbNotLike(String value) {
            addCriterion("BMJB not like", value, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbIn(List<String> values) {
            addCriterion("BMJB in", values, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbNotIn(List<String> values) {
            addCriterion("BMJB not in", values, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbBetween(String value1, String value2) {
            addCriterion("BMJB between", value1, value2, "bmjb");
            return (Criteria) this;
        }

        public Criteria andBmjbNotBetween(String value1, String value2) {
            addCriterion("BMJB not between", value1, value2, "bmjb");
            return (Criteria) this;
        }

        public Criteria andJkyhIsNull() {
            addCriterion("JKYH is null");
            return (Criteria) this;
        }

        public Criteria andJkyhIsNotNull() {
            addCriterion("JKYH is not null");
            return (Criteria) this;
        }

        public Criteria andJkyhEqualTo(String value) {
            addCriterion("JKYH =", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhNotEqualTo(String value) {
            addCriterion("JKYH <>", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhGreaterThan(String value) {
            addCriterion("JKYH >", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhGreaterThanOrEqualTo(String value) {
            addCriterion("JKYH >=", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhLessThan(String value) {
            addCriterion("JKYH <", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhLessThanOrEqualTo(String value) {
            addCriterion("JKYH <=", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhLike(String value) {
            addCriterion("JKYH like", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhNotLike(String value) {
            addCriterion("JKYH not like", value, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhIn(List<String> values) {
            addCriterion("JKYH in", values, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhNotIn(List<String> values) {
            addCriterion("JKYH not in", values, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhBetween(String value1, String value2) {
            addCriterion("JKYH between", value1, value2, "jkyh");
            return (Criteria) this;
        }

        public Criteria andJkyhNotBetween(String value1, String value2) {
            addCriterion("JKYH not between", value1, value2, "jkyh");
            return (Criteria) this;
        }

        public Criteria andSsjgIsNull() {
            addCriterion("SSJG is null");
            return (Criteria) this;
        }

        public Criteria andSsjgIsNotNull() {
            addCriterion("SSJG is not null");
            return (Criteria) this;
        }

        public Criteria andSsjgEqualTo(String value) {
            addCriterion("SSJG =", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgNotEqualTo(String value) {
            addCriterion("SSJG <>", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgGreaterThan(String value) {
            addCriterion("SSJG >", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgGreaterThanOrEqualTo(String value) {
            addCriterion("SSJG >=", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgLessThan(String value) {
            addCriterion("SSJG <", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgLessThanOrEqualTo(String value) {
            addCriterion("SSJG <=", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgLike(String value) {
            addCriterion("SSJG like", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgNotLike(String value) {
            addCriterion("SSJG not like", value, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgIn(List<String> values) {
            addCriterion("SSJG in", values, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgNotIn(List<String> values) {
            addCriterion("SSJG not in", values, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgBetween(String value1, String value2) {
            addCriterion("SSJG between", value1, value2, "ssjg");
            return (Criteria) this;
        }

        public Criteria andSsjgNotBetween(String value1, String value2) {
            addCriterion("SSJG not between", value1, value2, "ssjg");
            return (Criteria) this;
        }

        public Criteria andFyjgIsNull() {
            addCriterion("FYJG is null");
            return (Criteria) this;
        }

        public Criteria andFyjgIsNotNull() {
            addCriterion("FYJG is not null");
            return (Criteria) this;
        }

        public Criteria andFyjgEqualTo(String value) {
            addCriterion("FYJG =", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgNotEqualTo(String value) {
            addCriterion("FYJG <>", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgGreaterThan(String value) {
            addCriterion("FYJG >", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgGreaterThanOrEqualTo(String value) {
            addCriterion("FYJG >=", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgLessThan(String value) {
            addCriterion("FYJG <", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgLessThanOrEqualTo(String value) {
            addCriterion("FYJG <=", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgLike(String value) {
            addCriterion("FYJG like", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgNotLike(String value) {
            addCriterion("FYJG not like", value, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgIn(List<String> values) {
            addCriterion("FYJG in", values, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgNotIn(List<String> values) {
            addCriterion("FYJG not in", values, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgBetween(String value1, String value2) {
            addCriterion("FYJG between", value1, value2, "fyjg");
            return (Criteria) this;
        }

        public Criteria andFyjgNotBetween(String value1, String value2) {
            addCriterion("FYJG not between", value1, value2, "fyjg");
            return (Criteria) this;
        }

        public Criteria andDdqzIsNull() {
            addCriterion("DDQZ is null");
            return (Criteria) this;
        }

        public Criteria andDdqzIsNotNull() {
            addCriterion("DDQZ is not null");
            return (Criteria) this;
        }

        public Criteria andDdqzEqualTo(String value) {
            addCriterion("DDQZ =", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzNotEqualTo(String value) {
            addCriterion("DDQZ <>", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzGreaterThan(String value) {
            addCriterion("DDQZ >", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzGreaterThanOrEqualTo(String value) {
            addCriterion("DDQZ >=", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzLessThan(String value) {
            addCriterion("DDQZ <", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzLessThanOrEqualTo(String value) {
            addCriterion("DDQZ <=", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzLike(String value) {
            addCriterion("DDQZ like", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzNotLike(String value) {
            addCriterion("DDQZ not like", value, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzIn(List<String> values) {
            addCriterion("DDQZ in", values, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzNotIn(List<String> values) {
            addCriterion("DDQZ not in", values, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzBetween(String value1, String value2) {
            addCriterion("DDQZ between", value1, value2, "ddqz");
            return (Criteria) this;
        }

        public Criteria andDdqzNotBetween(String value1, String value2) {
            addCriterion("DDQZ not between", value1, value2, "ddqz");
            return (Criteria) this;
        }

        public Criteria andPxyjIsNull() {
            addCriterion("PXYJ is null");
            return (Criteria) this;
        }

        public Criteria andPxyjIsNotNull() {
            addCriterion("PXYJ is not null");
            return (Criteria) this;
        }

        public Criteria andPxyjEqualTo(String value) {
            addCriterion("PXYJ =", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjNotEqualTo(String value) {
            addCriterion("PXYJ <>", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjGreaterThan(String value) {
            addCriterion("PXYJ >", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjGreaterThanOrEqualTo(String value) {
            addCriterion("PXYJ >=", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjLessThan(String value) {
            addCriterion("PXYJ <", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjLessThanOrEqualTo(String value) {
            addCriterion("PXYJ <=", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjLike(String value) {
            addCriterion("PXYJ like", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjNotLike(String value) {
            addCriterion("PXYJ not like", value, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjIn(List<String> values) {
            addCriterion("PXYJ in", values, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjNotIn(List<String> values) {
            addCriterion("PXYJ not in", values, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjBetween(String value1, String value2) {
            addCriterion("PXYJ between", value1, value2, "pxyj");
            return (Criteria) this;
        }

        public Criteria andPxyjNotBetween(String value1, String value2) {
            addCriterion("PXYJ not between", value1, value2, "pxyj");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmIsNull() {
            addCriterion("XZCFJGBM is null");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmIsNotNull() {
            addCriterion("XZCFJGBM is not null");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmEqualTo(String value) {
            addCriterion("XZCFJGBM =", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmNotEqualTo(String value) {
            addCriterion("XZCFJGBM <>", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmGreaterThan(String value) {
            addCriterion("XZCFJGBM >", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmGreaterThanOrEqualTo(String value) {
            addCriterion("XZCFJGBM >=", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmLessThan(String value) {
            addCriterion("XZCFJGBM <", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmLessThanOrEqualTo(String value) {
            addCriterion("XZCFJGBM <=", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmLike(String value) {
            addCriterion("XZCFJGBM like", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmNotLike(String value) {
            addCriterion("XZCFJGBM not like", value, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmIn(List<String> values) {
            addCriterion("XZCFJGBM in", values, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmNotIn(List<String> values) {
            addCriterion("XZCFJGBM not in", values, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmBetween(String value1, String value2) {
            addCriterion("XZCFJGBM between", value1, value2, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andXzcfjgbmNotBetween(String value1, String value2) {
            addCriterion("XZCFJGBM not between", value1, value2, "xzcfjgbm");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcIsNull() {
            addCriterion("WZCLBMMC is null");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcIsNotNull() {
            addCriterion("WZCLBMMC is not null");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcEqualTo(String value) {
            addCriterion("WZCLBMMC =", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcNotEqualTo(String value) {
            addCriterion("WZCLBMMC <>", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcGreaterThan(String value) {
            addCriterion("WZCLBMMC >", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcGreaterThanOrEqualTo(String value) {
            addCriterion("WZCLBMMC >=", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcLessThan(String value) {
            addCriterion("WZCLBMMC <", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcLessThanOrEqualTo(String value) {
            addCriterion("WZCLBMMC <=", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcLike(String value) {
            addCriterion("WZCLBMMC like", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcNotLike(String value) {
            addCriterion("WZCLBMMC not like", value, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcIn(List<String> values) {
            addCriterion("WZCLBMMC in", values, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcNotIn(List<String> values) {
            addCriterion("WZCLBMMC not in", values, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcBetween(String value1, String value2) {
            addCriterion("WZCLBMMC between", value1, value2, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andWzclbmmcNotBetween(String value1, String value2) {
            addCriterion("WZCLBMMC not between", value1, value2, "wzclbmmc");
            return (Criteria) this;
        }

        public Criteria andSgcldIsNull() {
            addCriterion("SGCLD is null");
            return (Criteria) this;
        }

        public Criteria andSgcldIsNotNull() {
            addCriterion("SGCLD is not null");
            return (Criteria) this;
        }

        public Criteria andSgcldEqualTo(String value) {
            addCriterion("SGCLD =", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldNotEqualTo(String value) {
            addCriterion("SGCLD <>", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldGreaterThan(String value) {
            addCriterion("SGCLD >", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldGreaterThanOrEqualTo(String value) {
            addCriterion("SGCLD >=", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldLessThan(String value) {
            addCriterion("SGCLD <", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldLessThanOrEqualTo(String value) {
            addCriterion("SGCLD <=", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldLike(String value) {
            addCriterion("SGCLD like", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldNotLike(String value) {
            addCriterion("SGCLD not like", value, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldIn(List<String> values) {
            addCriterion("SGCLD in", values, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldNotIn(List<String> values) {
            addCriterion("SGCLD not in", values, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldBetween(String value1, String value2) {
            addCriterion("SGCLD between", value1, value2, "sgcld");
            return (Criteria) this;
        }

        public Criteria andSgcldNotBetween(String value1, String value2) {
            addCriterion("SGCLD not between", value1, value2, "sgcld");
            return (Criteria) this;
        }

        public Criteria andJdstt1IsNull() {
            addCriterion("JDSTT1 is null");
            return (Criteria) this;
        }

        public Criteria andJdstt1IsNotNull() {
            addCriterion("JDSTT1 is not null");
            return (Criteria) this;
        }

        public Criteria andJdstt1EqualTo(String value) {
            addCriterion("JDSTT1 =", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1NotEqualTo(String value) {
            addCriterion("JDSTT1 <>", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1GreaterThan(String value) {
            addCriterion("JDSTT1 >", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1GreaterThanOrEqualTo(String value) {
            addCriterion("JDSTT1 >=", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1LessThan(String value) {
            addCriterion("JDSTT1 <", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1LessThanOrEqualTo(String value) {
            addCriterion("JDSTT1 <=", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1Like(String value) {
            addCriterion("JDSTT1 like", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1NotLike(String value) {
            addCriterion("JDSTT1 not like", value, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1In(List<String> values) {
            addCriterion("JDSTT1 in", values, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1NotIn(List<String> values) {
            addCriterion("JDSTT1 not in", values, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1Between(String value1, String value2) {
            addCriterion("JDSTT1 between", value1, value2, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt1NotBetween(String value1, String value2) {
            addCriterion("JDSTT1 not between", value1, value2, "jdstt1");
            return (Criteria) this;
        }

        public Criteria andJdstt2IsNull() {
            addCriterion("JDSTT2 is null");
            return (Criteria) this;
        }

        public Criteria andJdstt2IsNotNull() {
            addCriterion("JDSTT2 is not null");
            return (Criteria) this;
        }

        public Criteria andJdstt2EqualTo(String value) {
            addCriterion("JDSTT2 =", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2NotEqualTo(String value) {
            addCriterion("JDSTT2 <>", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2GreaterThan(String value) {
            addCriterion("JDSTT2 >", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2GreaterThanOrEqualTo(String value) {
            addCriterion("JDSTT2 >=", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2LessThan(String value) {
            addCriterion("JDSTT2 <", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2LessThanOrEqualTo(String value) {
            addCriterion("JDSTT2 <=", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2Like(String value) {
            addCriterion("JDSTT2 like", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2NotLike(String value) {
            addCriterion("JDSTT2 not like", value, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2In(List<String> values) {
            addCriterion("JDSTT2 in", values, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2NotIn(List<String> values) {
            addCriterion("JDSTT2 not in", values, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2Between(String value1, String value2) {
            addCriterion("JDSTT2 between", value1, value2, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt2NotBetween(String value1, String value2) {
            addCriterion("JDSTT2 not between", value1, value2, "jdstt2");
            return (Criteria) this;
        }

        public Criteria andJdstt3IsNull() {
            addCriterion("JDSTT3 is null");
            return (Criteria) this;
        }

        public Criteria andJdstt3IsNotNull() {
            addCriterion("JDSTT3 is not null");
            return (Criteria) this;
        }

        public Criteria andJdstt3EqualTo(String value) {
            addCriterion("JDSTT3 =", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3NotEqualTo(String value) {
            addCriterion("JDSTT3 <>", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3GreaterThan(String value) {
            addCriterion("JDSTT3 >", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3GreaterThanOrEqualTo(String value) {
            addCriterion("JDSTT3 >=", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3LessThan(String value) {
            addCriterion("JDSTT3 <", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3LessThanOrEqualTo(String value) {
            addCriterion("JDSTT3 <=", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3Like(String value) {
            addCriterion("JDSTT3 like", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3NotLike(String value) {
            addCriterion("JDSTT3 not like", value, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3In(List<String> values) {
            addCriterion("JDSTT3 in", values, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3NotIn(List<String> values) {
            addCriterion("JDSTT3 not in", values, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3Between(String value1, String value2) {
            addCriterion("JDSTT3 between", value1, value2, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt3NotBetween(String value1, String value2) {
            addCriterion("JDSTT3 not between", value1, value2, "jdstt3");
            return (Criteria) this;
        }

        public Criteria andJdstt4IsNull() {
            addCriterion("JDSTT4 is null");
            return (Criteria) this;
        }

        public Criteria andJdstt4IsNotNull() {
            addCriterion("JDSTT4 is not null");
            return (Criteria) this;
        }

        public Criteria andJdstt4EqualTo(String value) {
            addCriterion("JDSTT4 =", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4NotEqualTo(String value) {
            addCriterion("JDSTT4 <>", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4GreaterThan(String value) {
            addCriterion("JDSTT4 >", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4GreaterThanOrEqualTo(String value) {
            addCriterion("JDSTT4 >=", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4LessThan(String value) {
            addCriterion("JDSTT4 <", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4LessThanOrEqualTo(String value) {
            addCriterion("JDSTT4 <=", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4Like(String value) {
            addCriterion("JDSTT4 like", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4NotLike(String value) {
            addCriterion("JDSTT4 not like", value, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4In(List<String> values) {
            addCriterion("JDSTT4 in", values, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4NotIn(List<String> values) {
            addCriterion("JDSTT4 not in", values, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4Between(String value1, String value2) {
            addCriterion("JDSTT4 between", value1, value2, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andJdstt4NotBetween(String value1, String value2) {
            addCriterion("JDSTT4 not between", value1, value2, "jdstt4");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSadjbttIsNull() {
            addCriterion("SADJBTT is null");
            return (Criteria) this;
        }

        public Criteria andSadjbttIsNotNull() {
            addCriterion("SADJBTT is not null");
            return (Criteria) this;
        }

        public Criteria andSadjbttEqualTo(String value) {
            addCriterion("SADJBTT =", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttNotEqualTo(String value) {
            addCriterion("SADJBTT <>", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttGreaterThan(String value) {
            addCriterion("SADJBTT >", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttGreaterThanOrEqualTo(String value) {
            addCriterion("SADJBTT >=", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttLessThan(String value) {
            addCriterion("SADJBTT <", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttLessThanOrEqualTo(String value) {
            addCriterion("SADJBTT <=", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttLike(String value) {
            addCriterion("SADJBTT like", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttNotLike(String value) {
            addCriterion("SADJBTT not like", value, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttIn(List<String> values) {
            addCriterion("SADJBTT in", values, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttNotIn(List<String> values) {
            addCriterion("SADJBTT not in", values, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttBetween(String value1, String value2) {
            addCriterion("SADJBTT between", value1, value2, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andSadjbttNotBetween(String value1, String value2) {
            addCriterion("SADJBTT not between", value1, value2, "sadjbtt");
            return (Criteria) this;
        }

        public Criteria andGzbltt1IsNull() {
            addCriterion("GZBLTT1 is null");
            return (Criteria) this;
        }

        public Criteria andGzbltt1IsNotNull() {
            addCriterion("GZBLTT1 is not null");
            return (Criteria) this;
        }

        public Criteria andGzbltt1EqualTo(String value) {
            addCriterion("GZBLTT1 =", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1NotEqualTo(String value) {
            addCriterion("GZBLTT1 <>", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1GreaterThan(String value) {
            addCriterion("GZBLTT1 >", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1GreaterThanOrEqualTo(String value) {
            addCriterion("GZBLTT1 >=", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1LessThan(String value) {
            addCriterion("GZBLTT1 <", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1LessThanOrEqualTo(String value) {
            addCriterion("GZBLTT1 <=", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1Like(String value) {
            addCriterion("GZBLTT1 like", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1NotLike(String value) {
            addCriterion("GZBLTT1 not like", value, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1In(List<String> values) {
            addCriterion("GZBLTT1 in", values, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1NotIn(List<String> values) {
            addCriterion("GZBLTT1 not in", values, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1Between(String value1, String value2) {
            addCriterion("GZBLTT1 between", value1, value2, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt1NotBetween(String value1, String value2) {
            addCriterion("GZBLTT1 not between", value1, value2, "gzbltt1");
            return (Criteria) this;
        }

        public Criteria andGzbltt2IsNull() {
            addCriterion("GZBLTT2 is null");
            return (Criteria) this;
        }

        public Criteria andGzbltt2IsNotNull() {
            addCriterion("GZBLTT2 is not null");
            return (Criteria) this;
        }

        public Criteria andGzbltt2EqualTo(String value) {
            addCriterion("GZBLTT2 =", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2NotEqualTo(String value) {
            addCriterion("GZBLTT2 <>", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2GreaterThan(String value) {
            addCriterion("GZBLTT2 >", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2GreaterThanOrEqualTo(String value) {
            addCriterion("GZBLTT2 >=", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2LessThan(String value) {
            addCriterion("GZBLTT2 <", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2LessThanOrEqualTo(String value) {
            addCriterion("GZBLTT2 <=", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2Like(String value) {
            addCriterion("GZBLTT2 like", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2NotLike(String value) {
            addCriterion("GZBLTT2 not like", value, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2In(List<String> values) {
            addCriterion("GZBLTT2 in", values, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2NotIn(List<String> values) {
            addCriterion("GZBLTT2 not in", values, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2Between(String value1, String value2) {
            addCriterion("GZBLTT2 between", value1, value2, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andGzbltt2NotBetween(String value1, String value2) {
            addCriterion("GZBLTT2 not between", value1, value2, "gzbltt2");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttIsNull() {
            addCriterion("QZCSSPBTT is null");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttIsNotNull() {
            addCriterion("QZCSSPBTT is not null");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttEqualTo(String value) {
            addCriterion("QZCSSPBTT =", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttNotEqualTo(String value) {
            addCriterion("QZCSSPBTT <>", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttGreaterThan(String value) {
            addCriterion("QZCSSPBTT >", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttGreaterThanOrEqualTo(String value) {
            addCriterion("QZCSSPBTT >=", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttLessThan(String value) {
            addCriterion("QZCSSPBTT <", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttLessThanOrEqualTo(String value) {
            addCriterion("QZCSSPBTT <=", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttLike(String value) {
            addCriterion("QZCSSPBTT like", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttNotLike(String value) {
            addCriterion("QZCSSPBTT not like", value, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttIn(List<String> values) {
            addCriterion("QZCSSPBTT in", values, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttNotIn(List<String> values) {
            addCriterion("QZCSSPBTT not in", values, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttBetween(String value1, String value2) {
            addCriterion("QZCSSPBTT between", value1, value2, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andQzcsspbttNotBetween(String value1, String value2) {
            addCriterion("QZCSSPBTT not between", value1, value2, "qzcsspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttIsNull() {
            addCriterion("XZCFSPBTT is null");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttIsNotNull() {
            addCriterion("XZCFSPBTT is not null");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttEqualTo(String value) {
            addCriterion("XZCFSPBTT =", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttNotEqualTo(String value) {
            addCriterion("XZCFSPBTT <>", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttGreaterThan(String value) {
            addCriterion("XZCFSPBTT >", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttGreaterThanOrEqualTo(String value) {
            addCriterion("XZCFSPBTT >=", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttLessThan(String value) {
            addCriterion("XZCFSPBTT <", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttLessThanOrEqualTo(String value) {
            addCriterion("XZCFSPBTT <=", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttLike(String value) {
            addCriterion("XZCFSPBTT like", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttNotLike(String value) {
            addCriterion("XZCFSPBTT not like", value, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttIn(List<String> values) {
            addCriterion("XZCFSPBTT in", values, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttNotIn(List<String> values) {
            addCriterion("XZCFSPBTT not in", values, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttBetween(String value1, String value2) {
            addCriterion("XZCFSPBTT between", value1, value2, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andXzcfspbttNotBetween(String value1, String value2) {
            addCriterion("XZCFSPBTT not between", value1, value2, "xzcfspbtt");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1IsNull() {
            addCriterion("CFJDSTT1 is null");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1IsNotNull() {
            addCriterion("CFJDSTT1 is not null");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1EqualTo(String value) {
            addCriterion("CFJDSTT1 =", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1NotEqualTo(String value) {
            addCriterion("CFJDSTT1 <>", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1GreaterThan(String value) {
            addCriterion("CFJDSTT1 >", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1GreaterThanOrEqualTo(String value) {
            addCriterion("CFJDSTT1 >=", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1LessThan(String value) {
            addCriterion("CFJDSTT1 <", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1LessThanOrEqualTo(String value) {
            addCriterion("CFJDSTT1 <=", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1Like(String value) {
            addCriterion("CFJDSTT1 like", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1NotLike(String value) {
            addCriterion("CFJDSTT1 not like", value, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1In(List<String> values) {
            addCriterion("CFJDSTT1 in", values, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1NotIn(List<String> values) {
            addCriterion("CFJDSTT1 not in", values, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1Between(String value1, String value2) {
            addCriterion("CFJDSTT1 between", value1, value2, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt1NotBetween(String value1, String value2) {
            addCriterion("CFJDSTT1 not between", value1, value2, "cfjdstt1");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2IsNull() {
            addCriterion("CFJDSTT2 is null");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2IsNotNull() {
            addCriterion("CFJDSTT2 is not null");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2EqualTo(String value) {
            addCriterion("CFJDSTT2 =", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2NotEqualTo(String value) {
            addCriterion("CFJDSTT2 <>", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2GreaterThan(String value) {
            addCriterion("CFJDSTT2 >", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2GreaterThanOrEqualTo(String value) {
            addCriterion("CFJDSTT2 >=", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2LessThan(String value) {
            addCriterion("CFJDSTT2 <", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2LessThanOrEqualTo(String value) {
            addCriterion("CFJDSTT2 <=", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2Like(String value) {
            addCriterion("CFJDSTT2 like", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2NotLike(String value) {
            addCriterion("CFJDSTT2 not like", value, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2In(List<String> values) {
            addCriterion("CFJDSTT2 in", values, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2NotIn(List<String> values) {
            addCriterion("CFJDSTT2 not in", values, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2Between(String value1, String value2) {
            addCriterion("CFJDSTT2 between", value1, value2, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andCfjdstt2NotBetween(String value1, String value2) {
            addCriterion("CFJDSTT2 not between", value1, value2, "cfjdstt2");
            return (Criteria) this;
        }

        public Criteria andTzdwttIsNull() {
            addCriterion("TZDWTT is null");
            return (Criteria) this;
        }

        public Criteria andTzdwttIsNotNull() {
            addCriterion("TZDWTT is not null");
            return (Criteria) this;
        }

        public Criteria andTzdwttEqualTo(String value) {
            addCriterion("TZDWTT =", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttNotEqualTo(String value) {
            addCriterion("TZDWTT <>", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttGreaterThan(String value) {
            addCriterion("TZDWTT >", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttGreaterThanOrEqualTo(String value) {
            addCriterion("TZDWTT >=", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttLessThan(String value) {
            addCriterion("TZDWTT <", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttLessThanOrEqualTo(String value) {
            addCriterion("TZDWTT <=", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttLike(String value) {
            addCriterion("TZDWTT like", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttNotLike(String value) {
            addCriterion("TZDWTT not like", value, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttIn(List<String> values) {
            addCriterion("TZDWTT in", values, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttNotIn(List<String> values) {
            addCriterion("TZDWTT not in", values, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttBetween(String value1, String value2) {
            addCriterion("TZDWTT between", value1, value2, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andTzdwttNotBetween(String value1, String value2) {
            addCriterion("TZDWTT not between", value1, value2, "tzdwtt");
            return (Criteria) this;
        }

        public Criteria andRksjIsNull() {
            addCriterion("rksj is null");
            return (Criteria) this;
        }

        public Criteria andRksjIsNotNull() {
            addCriterion("rksj is not null");
            return (Criteria) this;
        }

        public Criteria andRksjEqualTo(Date value) {
            addCriterion("rksj =", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotEqualTo(Date value) {
            addCriterion("rksj <>", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThan(Date value) {
            addCriterion("rksj >", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThanOrEqualTo(Date value) {
            addCriterion("rksj >=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThan(Date value) {
            addCriterion("rksj <", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThanOrEqualTo(Date value) {
            addCriterion("rksj <=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjIn(List<Date> values) {
            addCriterion("rksj in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotIn(List<Date> values) {
            addCriterion("rksj not in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjBetween(Date value1, Date value2) {
            addCriterion("rksj between", value1, value2, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotBetween(Date value1, Date value2) {
            addCriterion("rksj not between", value1, value2, "rksj");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andZsbjIsNull() {
            addCriterion("zsbj is null");
            return (Criteria) this;
        }

        public Criteria andZsbjIsNotNull() {
            addCriterion("zsbj is not null");
            return (Criteria) this;
        }

        public Criteria andZsbjEqualTo(String value) {
            addCriterion("zsbj =", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjNotEqualTo(String value) {
            addCriterion("zsbj <>", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjGreaterThan(String value) {
            addCriterion("zsbj >", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjGreaterThanOrEqualTo(String value) {
            addCriterion("zsbj >=", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjLessThan(String value) {
            addCriterion("zsbj <", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjLessThanOrEqualTo(String value) {
            addCriterion("zsbj <=", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjLike(String value) {
            addCriterion("zsbj like", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjNotLike(String value) {
            addCriterion("zsbj not like", value, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjIn(List<String> values) {
            addCriterion("zsbj in", values, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjNotIn(List<String> values) {
            addCriterion("zsbj not in", values, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjBetween(String value1, String value2) {
            addCriterion("zsbj between", value1, value2, "zsbj");
            return (Criteria) this;
        }

        public Criteria andZsbjNotBetween(String value1, String value2) {
            addCriterion("zsbj not between", value1, value2, "zsbj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_depart
     *
     * @mbg.generated do_not_delete_during_merge Mon May 27 16:24:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_depart
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}