package com.hkd.model.po;

import java.util.ArrayList;
import java.util.List;

public class TpUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public TpUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMjjhIsNull() {
            addCriterion("mjjh is null");
            return (Criteria) this;
        }

        public Criteria andMjjhIsNotNull() {
            addCriterion("mjjh is not null");
            return (Criteria) this;
        }

        public Criteria andMjjhEqualTo(String value) {
            addCriterion("mjjh =", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhNotEqualTo(String value) {
            addCriterion("mjjh <>", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhGreaterThan(String value) {
            addCriterion("mjjh >", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhGreaterThanOrEqualTo(String value) {
            addCriterion("mjjh >=", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhLessThan(String value) {
            addCriterion("mjjh <", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhLessThanOrEqualTo(String value) {
            addCriterion("mjjh <=", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhLike(String value) {
            addCriterion("mjjh like", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhNotLike(String value) {
            addCriterion("mjjh not like", value, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhIn(List<String> values) {
            addCriterion("mjjh in", values, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhNotIn(List<String> values) {
            addCriterion("mjjh not in", values, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhBetween(String value1, String value2) {
            addCriterion("mjjh between", value1, value2, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjjhNotBetween(String value1, String value2) {
            addCriterion("mjjh not between", value1, value2, "mjjh");
            return (Criteria) this;
        }

        public Criteria andMjxmIsNull() {
            addCriterion("mjxm is null");
            return (Criteria) this;
        }

        public Criteria andMjxmIsNotNull() {
            addCriterion("mjxm is not null");
            return (Criteria) this;
        }

        public Criteria andMjxmEqualTo(String value) {
            addCriterion("mjxm =", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmNotEqualTo(String value) {
            addCriterion("mjxm <>", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmGreaterThan(String value) {
            addCriterion("mjxm >", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmGreaterThanOrEqualTo(String value) {
            addCriterion("mjxm >=", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmLessThan(String value) {
            addCriterion("mjxm <", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmLessThanOrEqualTo(String value) {
            addCriterion("mjxm <=", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmLike(String value) {
            addCriterion("mjxm like", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmNotLike(String value) {
            addCriterion("mjxm not like", value, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmIn(List<String> values) {
            addCriterion("mjxm in", values, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmNotIn(List<String> values) {
            addCriterion("mjxm not in", values, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmBetween(String value1, String value2) {
            addCriterion("mjxm between", value1, value2, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjxmNotBetween(String value1, String value2) {
            addCriterion("mjxm not between", value1, value2, "mjxm");
            return (Criteria) this;
        }

        public Criteria andMjbmIsNull() {
            addCriterion("mjbm is null");
            return (Criteria) this;
        }

        public Criteria andMjbmIsNotNull() {
            addCriterion("mjbm is not null");
            return (Criteria) this;
        }

        public Criteria andMjbmEqualTo(String value) {
            addCriterion("mjbm =", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmNotEqualTo(String value) {
            addCriterion("mjbm <>", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmGreaterThan(String value) {
            addCriterion("mjbm >", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmGreaterThanOrEqualTo(String value) {
            addCriterion("mjbm >=", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmLessThan(String value) {
            addCriterion("mjbm <", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmLessThanOrEqualTo(String value) {
            addCriterion("mjbm <=", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmLike(String value) {
            addCriterion("mjbm like", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmNotLike(String value) {
            addCriterion("mjbm not like", value, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmIn(List<String> values) {
            addCriterion("mjbm in", values, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmNotIn(List<String> values) {
            addCriterion("mjbm not in", values, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmBetween(String value1, String value2) {
            addCriterion("mjbm between", value1, value2, "mjbm");
            return (Criteria) this;
        }

        public Criteria andMjbmNotBetween(String value1, String value2) {
            addCriterion("mjbm not between", value1, value2, "mjbm");
            return (Criteria) this;
        }

        public Criteria andSfzhIsNull() {
            addCriterion("sfzh is null");
            return (Criteria) this;
        }

        public Criteria andSfzhIsNotNull() {
            addCriterion("sfzh is not null");
            return (Criteria) this;
        }

        public Criteria andSfzhEqualTo(String value) {
            addCriterion("sfzh =", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotEqualTo(String value) {
            addCriterion("sfzh <>", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhGreaterThan(String value) {
            addCriterion("sfzh >", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhGreaterThanOrEqualTo(String value) {
            addCriterion("sfzh >=", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLessThan(String value) {
            addCriterion("sfzh <", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLessThanOrEqualTo(String value) {
            addCriterion("sfzh <=", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLike(String value) {
            addCriterion("sfzh like", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotLike(String value) {
            addCriterion("sfzh not like", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhIn(List<String> values) {
            addCriterion("sfzh in", values, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotIn(List<String> values) {
            addCriterion("sfzh not in", values, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhBetween(String value1, String value2) {
            addCriterion("sfzh between", value1, value2, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotBetween(String value1, String value2) {
            addCriterion("sfzh not between", value1, value2, "sfzh");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_user
     *
     * @mbg.generated do_not_delete_during_merge Tue May 28 15:52:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_user
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}