package com.hkd.model.dto;

import lombok.Data;

@Data
public class UserInfo {
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.mjjh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String mjjh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.mjxm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String mjxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.mjbm
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String mjbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user.sfzh
     *
     * @mbg.generated Tue May 28 15:52:54 CST 2019
     */
    private String sfzh;

    private Type type;

   public enum Type{
        IN(1,"输入");
        private int code;
        private String value;
        Type(int code,String value){
            this.code=code;
            this.value=value;
        }

        public int getCode() {
            return code;
        }

        public void setCode(int code) {
            this.code = code;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }
    }
}
