package cn.com.cybertech.sdly.mapper;

import cn.com.cybertech.sdly.model.po.TpRolePermission;
import cn.com.cybertech.sdly.model.po.TpRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    long countByExample(TpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int deleteByExample(TpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int insert(TpRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int insertSelective(TpRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    List<TpRolePermission> selectByExample(TpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    TpRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") TpRolePermission record, @Param("example") TpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByExample(@Param("record") TpRolePermission record, @Param("example") TpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByPrimaryKeySelective(TpRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_permission
     *
     * @mbg.generated Mon May 27 16:24:06 CST 2019
     */
    int updateByPrimaryKey(TpRolePermission record);
}